export enum TYPE {
  "BUG" = "BUG",
  "DARK" = "DARK",
  "DRAGON" = "DRAGON",
  "ELECTRIC" = "ELECTRIC",
  "FIGHTING" = "FIGHTING",
  "FIRE" = "FIRE",
  "FLYING" = "FLYING",
  "GHOST" = "GHOST",
  "GRASS" = "GRASS",
  "GROUND" = "GROUND",
  "ICE" = "ICE",
  "NORMAL" = "NORMAL",
  "POISON" = "POISON",
  "PSYCHIC" = "PSYCHIC",
  "ROCK" = "ROCK",
  "STEEL" = "STEEL",
  "WATER" = "WATER"
}

export const TYPES_LIST = [
  "BUG",
  "DARK",
  "DRAGON",
  "ELECTRIC",
  "FIGHTING",
  "FIRE",
  "FLYING",
  "GHOST",
  "GRASS",
  "GROUND",
  "ICE",
  "NORMAL",
  "POISON",
  "PSYCHIC",
  "ROCK",
  "STEEL",
  "WATER"
]

export const POKEMON = [
  "Bulbasaur",
  "Ivysaur",
  "Venusaur",
  "Charmander",
  "Charmeleon",
  "Charizard",
  "Squirtle",
  "Wartortle",
  "Blastoise",
  "Caterpie",
  "Metapod",
  "Butterfree",
  "Weedle",
  "Kakuna",
  "Beedrill",
  "Pidgey",
  "Pidgeotto",
  "Pidgeot",
  "Rattata",
  "Raticate",
  "Spearow",
  "Fearow",
  "Ekans",
  "Arbok",
  "Pikachu",
  "Raichu",
  "Sandshrew",
  "Sandslash",
  "NidoranF",
  "Nidorina",
  "Nidoqueen",
  "NidoranM",
  "Nidorino",
  "Nidoking",
  "Clefairy",
  "Clefable",
  "Vulpix",
  "Ninetales",
  "Jigglypuff",
  "Wigglytuff",
  "Zubat",
  "Golbat",
  "Oddish",
  "Gloom",
  "Vileplume",
  "Paras",
  "Parasect",
  "Venonat",
  "Venomoth",
  "Diglett",
  "Dugtrio",
  "Meowth",
  "Persian",
  "Psyduck",
  "Golduck",
  "Mankey",
  "Primeape",
  "Growlithe",
  "Arcanine",
  "Poliwag",
  "Poliwhirl",
  "Poliwrath",
  "Abra",
  "Kadabra",
  "Alakazam",
  "Machop",
  "Machoke",
  "Machamp",
  "Bellsprout",
  "Weepinbell",
  "Victreebel",
  "Tentacool",
  "Tentacruel",
  "Geodude",
  "Graveler",
  "Golem",
  "Ponyta",
  "Rapidash",
  "Slowpoke",
  "Slowbro",
  "Magnemite",
  "Magneton",
  "Farfetch'd",
  "Doduo",
  "Dodrio",
  "Seel",
  "Dewgong",
  "Grimer",
  "Muk",
  "Shellder",
  "Cloyster",
  "Gastly",
  "Haunter",
  "Gengar",
  "Onix",
  "Drowzee",
  "Hypno",
  "Krabby",
  "Kingler",
  "Voltorb",
  "Electrode",
  "Exeggcute",
  "Exeggutor",
  "Cubone",
  "Marowak",
  "Hitmonlee",
  "Hitmonchan",
  "Lickitung",
  "Koffing",
  "Weezing",
  "Rhyhorn",
  "Rhydon",
  "Chansey",
  "Tangela",
  "Kangaskhan",
  "Horsea",
  "Seadra",
  "Goldeen",
  "Seaking",
  "Staryu",
  "Starmie",
  "Mr.Mime",
  "Scyther",
  "Jynx",
  "Electabuzz",
  "Magmar",
  "Pinsir",
  "Tauros",
  "Magikarp",
  "Gyarados",
  "Lapras",
  "Ditto",
  "Eevee",
  "Vaporeon",
  "Jolteon",
  "Flareon",
  "Porygon",
  "Omanyte",
  "Omastar",
  "Kabuto",
  "Kabutops",
  "Aerodactyl",
  "Snorlax",
  "Articuno",
  "Zapdos",
  "Moltres",
  "Dratini",
  "Dragonair",
  "Dragonite",
  "Mewtwo",
  "Mew",
  "Chikorita",
  "Bayleef",
  "Meganium",
  "Cyndaquil",
  "Quilava",
  "Typhlosion",
  "Totodile",
  "Croconaw",
  "Feraligatr",
  "Sentret",
  "Furret",
  "Hoothoot",
  "Noctowl",
  "Ledyba",
  "Ledian",
  "Spinarak",
  "Ariados",
  "Crobat",
  "Chinchou",
  "Lanturn",
  "Pichu",
  "Cleffa",
  "Igglybuff",
  "Togepi",
  "Togetic",
  "Natu",
  "Xatu",
  "Mareep",
  "Flaaffy",
  "Ampharos",
  "Bellossom",
  "Marill",
  "Azumarill",
  "Sudowoodo",
  "Politoed",
  "Hoppip",
  "Skiploom",
  "Jumpluff",
  "Aipom",
  "Sunkern",
  "Sunflora",
  "Yanma",
  "Wooper",
  "Quagsire",
  "Espeon",
  "Umbreon",
  "Murkrow",
  "Slowking",
  "Misdreavus",
  "Unown",
  "Wobbuffet",
  "Girafarig",
  "Pineco",
  "Forretress",
  "Dunsparce",
  "Gligar",
  "Steelix",
  "Snubbull",
  "Granbull",
  "Qwilfish",
  "Scizor",
  "Shuckle",
  "Heracross",
  "Sneasel",
  "Teddiursa",
  "Ursaring",
  "Slugma",
  "Magcargo",
  "Swinub",
  "Piloswine",
  "Corsola",
  "Remoraid",
  "Octillery",
  "Delibird",
  "Mantine",
  "Skarmory",
  "Houndour",
  "Houndoom",
  "Kingdra",
  "Phanpy",
  "Donphan",
  "Porygon2",
  "Stantler",
  "Smeargle",
  "Tyrogue",
  "Hitmontop",
  "Smoochum",
  "Elekid",
  "Magby",
  "Miltank",
  "Blissey",
  "Raikou",
  "Entei",
  "Suicune",
  "Larvitar",
  "Pupitar",
  "Tyranitar",
  "Lugia",
  "Ho-oh",
  "Celebi",
  "Treecko",
  "Grovyle",
  "Sceptile",
  "Torchic",
  "Combusken",
  "Blaziken",
  "Mudkip",
  "Marshtomp",
  "Swampert",
  "Poochyena",
  "Mightyena",
  "Zigzagoon",
  "Linoone",
  "Wurmple",
  "Silcoon",
  "Beautifly",
  "Cascoon",
  "Dustox",
  "Lotad",
  "Lombre",
  "Ludicolo",
  "Seedot",
  "Nuzleaf",
  "Shiftry",
  "Taillow",
  "Swellow",
  "Wingull",
  "Pelipper",
  "Ralts",
  "Kirlia",
  "Gardevoir",
  "Surskit",
  "Masquerain",
  "Shroomish",
  "Breloom",
  "Slakoth",
  "Vigoroth",
  "Slaking",
  "Nincada",
  "Ninjask",
  "Shedinja",
  "Whismur",
  "Loudred",
  "Exploud",
  "Makuhita",
  "Hariyama",
  "Azurill",
  "Nosepass",
  "Skitty",
  "Delcatty",
  "Sableye",
  "Mawile",
  "Aron",
  "Lairon",
  "Aggron",
  "Meditite",
  "Medicham",
  "Electrike",
  "Manectric",
  "Plusle",
  "Minun",
  "Volbeat",
  "Illumise",
  "Roselia",
  "Gulpin",
  "Swalot",
  "Carvanha",
  "Sharpedo",
  "Wailmer",
  "Wailord",
  "Numel",
  "Camerupt",
  "Torkoal",
  "Spoink",
  "Grumpig",
  "Spinda",
  "Trapinch",
  "Vibrava",
  "Flygon",
  "Cacnea",
  "Cacturne",
  "Swablu",
  "Altaria",
  "Zangoose",
  "Seviper",
  "Lunatone",
  "Solrock",
  "Barboach",
  "Whiscash",
  "Corphish",
  "Crawdaunt",
  "Baltoy",
  "Claydol",
  "Lileep",
  "Cradily",
  "Anorith",
  "Armaldo",
  "Feebas",
  "Milotic",
  "Castform",
  "Kecleon",
  "Shuppet",
  "Banette",
  "Duskull",
  "Dusclops",
  "Tropius",
  "Chimecho",
  "Absol",
  "Wynaut",
  "Snorunt",
  "Glalie",
  "Spheal",
  "Sealeo",
  "Walrein",
  "Clamperl",
  "Huntail",
  "Gorebyss",
  "Relicanth",
  "Luvdisc",
  "Bagon",
  "Shelgon",
  "Salamence",
  "Beldum",
  "Metang",
  "Metagross",
  "Regirock",
  "Regice",
  "Registeel",
  "Latias",
  "Latios",
  "Kyogre",
  "Groudon",
  "Rayquaza",
  "Jirachi",
  "Deoxys",
  "Deoxys-attack",
  "Deoxys-defense",
  "Deoxys-speed",
  "Turtwig",
  "Grotle",
  "Torterra",
  "Chimchar",
  "Monferno",
  "Infernape",
  "Piplup",
  "Prinplup",
  "Empoleon",
  "Starly",
  "Staravia",
  "Staraptor",
  "Bidoof",
  "Bibarel",
  "Kricketot",
  "Kricketune",
  "Shinx",
  "Luxio",
  "Luxray",
  "Budew",
  "Roserade",
  "Cranidos",
  "Rampardos",
  "Shieldon",
  "Bastiodon",
  "Burmy",
  "Wormadam-plant",
  "Wormadam-sandy",
  "Wormadam-trash",
  "Mothim",
  "Combee",
  "Vespiquen",
  "Pachirisu",
  "Buizel",
  "Floatzel",
  "Cherubi",
  "Cherrim",
  "Shellos",
  "Gastrodon",
  "Ambipom",
  "Drifloon",
  "Drifblim",
  "Buneary",
  "Lopunny",
  "Mismagius",
  "Honchkrow",
  "Glameow",
  "Purugly",
  "Chingling",
  "Stunky",
  "Skuntank",
  "Bronzor",
  "Bronzong",
  "Bonsly",
  "Mime-jr",
  "Happiny",
  "Chatot",
  "Spiritomb",
  "Gible",
  "Gabite",
  "Garchomp",
  "Munchlax",
  "Riolu",
  "Lucario",
  "Hippopotas",
  "Hippowdon",
  "Skorupi",
  "Drapion",
  "Croagunk",
  "Toxicroak",
  "Carnivine",
  "Finneon",
  "Lumineon",
  "Mantyke",
  "Snover",
  "Abomasnow",
  "Weavile",
  "Magnezone",
  "Lickilicky",
  "Rhyperior",
  "Tangrowth",
  "Electivire",
  "Magmortar",
  "Togekiss",
  "Yanmega",
  "Leafeon",
  "Glaceon",
  "Gliscor",
  "Mamoswine",
  "Porygon-Z",
  "Gallade",
  "Probopass",
  "Dusknoir",
  "Froslass",
  "Rotom",
  "Rotom-heat",
  "Rotom-wash",
  "Rotom-frost",
  "Rotom-fan",
  "Rotom-mow",
  "Uxie",
  "Mesprit",
  "Azelf",
  "Dialga",
  "Palkia",
  "Heatran",
  "Regigigas",
  "Giratina-altered",
  "Giratina-origin",
  "Cresselia",
  "Phione",
  "Manaphy",
  "Darkrai",
  "Shaymin-land",
  "Shaymin-sky",
  "Arceus",
]
export const EVOLUTIONS_GROUPS_2 = {// PROBABLY RANDOMIZED IN A DIFFERENT WAY BECAUSE FOR EXAMPLE RALTS COULD BE SAME TYPE OF GARDEVOIR (THERE ISN'T GALLADE)
  "BULBASAUREVO": ["Bulbasaur", "Ivysaur", "Venusaur"],
  "CHARMANDEREVO": ["Charmander", "Charmeleon", "Charizard"],
  "SQUIRTLEVO": ["Squirtle", "Wartortle", "Blastoise"],
  "CATERPIEEVO": ["Caterpie", "Metapod", "Butterfree"],
  "WEEDLEEVO": ["Weedle", "Kakuna", "Beedrill"],
  "PIDGEYEVO": ["Pidgey", "Pidgeotto", "Pidgeot"],
  "RATTATAEVO": ["Rattata", "Raticate"],
  "SPEAROWEVO": ["Spearow", "Fearow"],
  "EKANSEVO": ["Ekans", "Arbok"],
  "PICHUEVO": ["Pichu", "Pikachu", "Raichu"],
  "SANDSHREWEVO": ["Sandshrew", "Sandslash"],
  "NIDORANFEVO": ["NidoranF", "Nidorina", "Nidoqueen"],
  "NIDORANMEVO": ["NidoranM", "Nidorino", "Nidoking"],
  "CLEFFAEVO": ["Cleffa", "Clefairy", "Clefable"],
  "VULPIXEVO": ["Vulpix", "Ninetales"],
  "IGGLYBUFFEVO": ["Igglybuff", "Jigglypuff", "Wigglytuff"],
  "ZUBATOEVO": ["Zubat", "Golbat", "Crobat"],
  "ODDISHEVO": ["Oddish", "Gloom"],
  "VILEPLUME": ["Vileplume"],
  "PARASEVO": ["Paras", "Parasect"],
  "VENONATEVO": ["Venonat", "Venomoth"],
  "DIGLETTEVO": ["Diglett", "Dugtrio"],
  "MEOWTHEVO": ["Meowth", "Persian"],
  "PSYDUCKEVO": ["Psyduck", "Golduck"],
  "MANKEYEVO": ["Mankey", "Primeape"],
  "GROWLITHEEVO": ["Growlithe", "Arcanine"],
  "POLIWAGEVO": ["Poliwag", "Poliwhirl"],
  "POLIWRATH": ["Poliwrath"],
  "ABRAEVO": ["Abra", "Kadabra", "Alakazam"],
  "MACHOPEVO": ["Machop", "Machoke", "Machamp"],
  "BELLSPROUTEVO": ["Bellsprout", "Weepinbell", "Victreebel"],
  "TENTACOOLEVO": ["Tentacool", "Tentacruel"],
  "GEODUDEEVO": ["Geodude", "Graveler", "Golem"],
  "PONYTAEVO": ["Ponyta", "Rapidash"],
  "SLOWPOKE": ["Slowpoke"],
  "SLOWBRO": ["Slowbro"],
  "MAGNEMITEEVO": ["Magnemite", "Magneton"],
  "FARFECTHD": ["Farfetch'd"],
  "DODUOEVO": ["Doduo", "Dodrio"],
  "SEELEVO": ["Seel", "Dewgong"],
  "GRIMEREVO": ["Grimer", "Muk"],
  "SHELLDEREVO": ["Shellder", "Cloyster"],
  "GASTLYEVO": ["Gastly", "Haunter", "Gengar"],
  "ONIXEVO": ["Onix", "Steelix"],
  "DROWZEEEVO": ["Drowzee", "Hypno"],
  "KRABBYEVO": ["Krabby", "Kingler"],
  "VOLTORBEVO": ["Voltorb", "Electrode"],
  "EXEGGCUTEEVO": ["Exeggcute", "Exeggutor"],
  "CUBONEEVO": ["Cubone", "Marowak"],
  "HITMONLEE": ["Hitmonlee"],
  "HITMONCHAN": ["Hitmonchan"],
  "LICKYTUNGEVO": ["Lickitung"],
  "KOFFINGEVO": ["Koffing", "Weezing"],
  "RHYHORNEVO": ["Rhyhorn", "Rhydon"],
  "HAPPINYEVO": ["Chansey", "Blissey"],
  "TANGELAEVO": ["Tangela"],
  "KANGASKHAN": ["Kangaskhan"],
  "HORSEAEVO": ["Horsea", "Seadra", "Kingdra"],
  "GOLDEENEVO": ["Goldeen", "Seaking"],
  "STARYUEVO": ["Staryu", "Starmie"],
  "MIMEJREVO": ["Mr.Mime"],
  "SCYTHEREVO": ["Scyther", "Scizor"],
  "SMOOCHUMEVO": ["Smoochum", "Jynx"],
  "ELEKIDEVO": ["Elekid", "Electabuzz"],
  "MAGBYEVO": ["Magby", "Magmar"],
  "PINSIR": ["Pinsir"],
  "TAUROS": ["Tauros"],
  "MAGKARPEVO": ["Magikarp", "Gyarados"],
  "LAPRAS": ["Lapras"],
  "DITTO": ["Ditto"],
  "EEVEE": ["Eevee"],
  "VAPOREON": ["Vaporeon"],
  "JOLTEON": ["Jolteon"],
  "FLAREON": ["Flareon"],
  "PORYGONEVO": ["Porygon", "Porygon2"],
  "OMANYTEEVO": ["Omanyte", "Omastar"],
  "KABUTOEVO": ["Kabuto", "Kabutops"],
  "AERODACTYL": ["Aerodactyl"],
  "MUNCHLAXEVO": ["Snorlax"],
  "ARTICUNO": ["Articuno"],
  "ZAPDOS": ["Zapdos"],
  "MOLTRES": ["Moltres"],
  "DRATINIEVO": ["Dratini", "Dragonair", "Dragonite"],
  "MEWTWO": ["Mewtwo"],
  "MEW": ["Mew"],
  "CHIKORITAEVO": ["Chikorita", "Bayleef", "Meganium"],
  "CYNDAQUILEVO": ["Cyndaquil", "Quilava", "Typhlosion"],
  "TOTODILEEVO": ["Totodile", "Croconaw", "Feraligatr"],
  "SENTRETEVO": ["Sentret", "Furret"],
  "HOOTHOOTEVO": ["Hoothoot", "Noctowl"],
  "LEDYBAEVO": ["Ledyba", "Ledian"],
  "SPINARAKEVO": ["Spinarak", "Ariados"],
  "CHINCHOUEVO": ["Chinchou", "Lanturn"],
  "TOGEPIEVO": ["Togepi", "Togetic"],
  "NATUEVO": ["Natu", "Xatu"],
  "MAREEPEVO": ["Mareep", "Flaaffy", "Ampharos"],
  "BELLOSSOM": ["Bellossom"],
  "AZURILLEVO": ["Marill", "Azumarill"],
  "BONSLYEVO": ["Sudowoodo"],
  "POLITOED": ["Politoed"],
  "HOPPIPEVO": ["Hoppip", "Skiploom", "Jumpluff"],
  "AIPOMEVO": ["Aipom"],
  "SUNKERNEVO": ["Sunkern", "Sunflora"],
  "YANMAEVO": ["Yanma"],
  "WOOPEREVO": ["Wooper", "Quagsire"],
  "ESPEON": ["Espeon"],
  "UMBREON": ["Umbreon"],
  "MURKROWEVO": ["Murkrow"],
  "SLOWKING": ["Slowking"],
  "MISDREAVUS": ["Misdreavus"],
  "UNOWN": ["Unown"],
  "WYNAUTEVO": ["Wobbuffet"],
  "GIRAFARIG": ["Girafarig"],
  "PINECOEVO": ["Pineco", "Forretress"],
  "DUNSPARCE": ["Dunsparce"],
  "GLIGAREVO": ["Gligar"],
  "SNUBBULLEVO": ["Snubbull", "Granbull"],
  "QWILFISH": ["Qwilfish"],
  "SHUCKLE": ["Shuckle"],
  "HERACROSS": ["Heracross"],
  "SNEASELEVO": ["Sneasel"],
  "TEDDIURSAEVO": ["Teddiursa", "Ursaring"],
  "SLUGMAEVO": ["Slugma", "Magcargo"],
  "SWINUBEVO": ["Swinub", "Piloswine"],
  "CORSOLA": ["Corsola"],
  "REMORAIDEVO": ["Remoraid", "Octillery"],
  "DELIBIRD": ["Delibird"],
  "MANTYKEEVO": ["Mantine"],
  "SKARMORY": ["Skarmory"],
  "HOUNDOUREVO": ["Houndour", "Houndoom"],
  "PHANPYEVO": ["Phanpy", "Donphan"],
  "STANTLER": ["Stantler"],
  "SMEARGLE": ["Smeargle"],
  "TYROGUE": ["Tyrogue"],
  "HITMONTOP": ["Hitmontop"],
  "MILTANK": ["Miltank"],
  "RAIKOU": ["Raikou"],
  "ENTEI": ["Entei"],
  "SUICUNE": ["Suicune"],
  "LARVITAREVO": ["Larvitar", "Pupitar", "Tyranitar"],
  "LUGIA": ["Lugia"],
  "HOOH": ["Ho-oh"],
  "CELEBI": ["Celebi"],
}

export const EVOLUTIONS_GROUPS_3 = { // PROBABLY RANDOMIZED IN A DIFFERENT WAY BECAUSE FOR EXAMPLE RALTS COULD BE SAME TYPE OF GARDEVOIR (THERE ISN'T GALLADE)
  "BULBASAUREVO": ["Bulbasaur", "Ivysaur", "Venusaur"],
  "CHARMANDEREVO": ["Charmander", "Charmeleon", "Charizard"],
  "SQUIRTLEVO": ["Squirtle", "Wartortle", "Blastoise"],
  "CATERPIEEVO": ["Caterpie", "Metapod", "Butterfree"],
  "WEEDLEEVO": ["Weedle", "Kakuna", "Beedrill"],
  "PIDGEYEVO": ["Pidgey", "Pidgeotto", "Pidgeot"],
  "RATTATAEVO": ["Rattata", "Raticate"],
  "SPEAROWEVO": ["Spearow", "Fearow"],
  "EKANSEVO": ["Ekans", "Arbok"],
  "PICHUEVO": ["Pichu", "Pikachu", "Raichu"],
  "SANDSHREWEVO": ["Sandshrew", "Sandslash"],
  "NIDORANFEVO": ["NidoranF", "Nidorina", "Nidoqueen"],
  "NIDORANMEVO": ["NidoranM", "Nidorino", "Nidoking"],
  "CLEFFAEVO": ["Cleffa", "Clefairy", "Clefable"],
  "VULPIXEVO": ["Vulpix", "Ninetales"],
  "IGGLYBUFFEVO": ["Igglybuff", "Jigglypuff", "Wigglytuff"],
  "ZUBATOEVO": ["Zubat", "Golbat", "Crobat"],
  "ODDISHEVO": ["Oddish", "Gloom"],
  "VILEPLUME": ["Vileplume"],
  "PARASEVO": ["Paras", "Parasect"],
  "VENONATEVO": ["Venonat", "Venomoth"],
  "DIGLETTEVO": ["Diglett", "Dugtrio"],
  "MEOWTHEVO": ["Meowth", "Persian"],
  "PSYDUCKEVO": ["Psyduck", "Golduck"],
  "MANKEYEVO": ["Mankey", "Primeape"],
  "GROWLITHEEVO": ["Growlithe", "Arcanine"],
  "POLIWAGEVO": ["Poliwag", "Poliwhirl"],
  "POLIWRATH": ["Poliwrath"],
  "ABRAEVO": ["Abra", "Kadabra", "Alakazam"],
  "MACHOPEVO": ["Machop", "Machoke", "Machamp"],
  "BELLSPROUTEVO": ["Bellsprout", "Weepinbell", "Victreebel"],
  "TENTACOOLEVO": ["Tentacool", "Tentacruel"],
  "GEODUDEEVO": ["Geodude", "Graveler", "Golem"],
  "PONYTAEVO": ["Ponyta", "Rapidash"],
  "SLOWPOKE": ["Slowpoke"],
  "SLOWBRO": ["Slowbro"],
  "MAGNEMITEEVO": ["Magnemite", "Magneton"],
  "FARFECTHD": ["Farfetch'd"],
  "DODUOEVO": ["Doduo", "Dodrio"],
  "SEELEVO": ["Seel", "Dewgong"],
  "GRIMEREVO": ["Grimer", "Muk"],
  "SHELLDEREVO": ["Shellder", "Cloyster"],
  "GASTLYEVO": ["Gastly", "Haunter", "Gengar"],
  "ONIXEVO": ["Onix", "Steelix"],
  "DROWZEEEVO": ["Drowzee", "Hypno"],
  "KRABBYEVO": ["Krabby", "Kingler"],
  "VOLTORBEVO": ["Voltorb", "Electrode"],
  "EXEGGCUTEEVO": ["Exeggcute", "Exeggutor"],
  "CUBONEEVO": ["Cubone", "Marowak"],
  "HITMONLEE": ["Hitmonlee"],
  "HITMONCHAN": ["Hitmonchan"],
  "LICKYTUNGEVO": ["Lickitung"],
  "KOFFINGEVO": ["Koffing", "Weezing"],
  "RHYHORNEVO": ["Rhyhorn", "Rhydon"],
  "HAPPINYEVO": ["Chansey", "Blissey"],
  "TANGELAEVO": ["Tangela"],
  "KANGASKHAN": ["Kangaskhan"],
  "HORSEAEVO": ["Horsea", "Seadra", "Kingdra"],
  "GOLDEENEVO": ["Goldeen", "Seaking"],
  "STARYUEVO": ["Staryu", "Starmie"],
  "MIMEJREVO": ["Mr.Mime"],
  "SCYTHEREVO": ["Scyther", "Scizor"],
  "SMOOCHUMEVO": ["Smoochum", "Jynx"],
  "ELEKIDEVO": ["Elekid", "Electabuzz"],
  "MAGBYEVO": ["Magby", "Magmar"],
  "PINSIR": ["Pinsir"],
  "TAUROS": ["Tauros"],
  "MAGKARPEVO": ["Magikarp", "Gyarados"],
  "LAPRAS": ["Lapras"],
  "DITTO": ["Ditto"],
  "EEVEE": ["Eevee"],
  "VAPOREON": ["Vaporeon"],
  "JOLTEON": ["Jolteon"],
  "FLAREON": ["Flareon"],
  "PORYGONEVO": ["Porygon", "Porygon2"],
  "OMANYTEEVO": ["Omanyte", "Omastar"],
  "KABUTOEVO": ["Kabuto", "Kabutops"],
  "AERODACTYL": ["Aerodactyl"],
  "MUNCHLAXEVO": ["Snorlax"],
  "ARTICUNO": ["Articuno"],
  "ZAPDOS": ["Zapdos"],
  "MOLTRES": ["Moltres"],
  "DRATINIEVO": ["Dratini", "Dragonair", "Dragonite"],
  "MEWTWO": ["Mewtwo"],
  "MEW": ["Mew"],
  "CHIKORITAEVO": ["Chikorita", "Bayleef", "Meganium"],
  "CYNDAQUILEVO": ["Cyndaquil", "Quilava", "Typhlosion"],
  "TOTODILEEVO": ["Totodile", "Croconaw", "Feraligatr"],
  "SENTRETEVO": ["Sentret", "Furret"],
  "HOOTHOOTEVO": ["Hoothoot", "Noctowl"],
  "LEDYBAEVO": ["Ledyba", "Ledian"],
  "SPINARAKEVO": ["Spinarak", "Ariados"],
  "CHINCHOUEVO": ["Chinchou", "Lanturn"],
  "TOGEPIEVO": ["Togepi", "Togetic"],
  "NATUEVO": ["Natu", "Xatu"],
  "MAREEPEVO": ["Mareep", "Flaaffy", "Ampharos"],
  "BELLOSSOM": ["Bellossom"],
  "AZURILLEVO": ["Azurill", "Marill", "Azumarill"],
  "BONSLYEVO": ["Sudowoodo"],
  "POLITOED": ["Politoed"],
  "HOPPIPEVO": ["Hoppip", "Skiploom", "Jumpluff"],
  "AIPOMEVO": ["Aipom"],
  "SUNKERNEVO": ["Sunkern", "Sunflora"],
  "YANMAEVO": ["Yanma"],
  "WOOPEREVO": ["Wooper", "Quagsire"],
  "ESPEON": ["Espeon"],
  "UMBREON": ["Umbreon"],
  "MURKROWEVO": ["Murkrow"],
  "SLOWKING": ["Slowking"],
  "MISDREAVUS": ["Misdreavus"],
  "UNOWN": ["Unown"],
  "WYNAUTEVO": ["Wynaut", "Wobbuffet"],
  "GIRAFARIG": ["Girafarig"],
  "PINECOEVO": ["Pineco", "Forretress"],
  "DUNSPARCE": ["Dunsparce"],
  "GLIGAREVO": ["Gligar"],
  "SNUBBULLEVO": ["Snubbull", "Granbull"],
  "QWILFISH": ["Qwilfish"],
  "SHUCKLE": ["Shuckle"],
  "HERACROSS": ["Heracross"],
  "SNEASELEVO": ["Sneasel"],
  "TEDDIURSAEVO": ["Teddiursa", "Ursaring"],
  "SLUGMAEVO": ["Slugma", "Magcargo"],
  "SWINUBEVO": ["Swinub", "Piloswine"],
  "CORSOLA": ["Corsola"],
  "REMORAIDEVO": ["Remoraid", "Octillery"],
  "DELIBIRD": ["Delibird"],
  "MANTYKEEVO": ["Mantine"],
  "SKARMORY": ["Skarmory"],
  "HOUNDOUREVO": ["Houndour", "Houndoom"],
  "PHANPYEVO": ["Phanpy", "Donphan"],
  "STANTLER": ["Stantler"],
  "SMEARGLE": ["Smeargle"],
  "TYROGUE": ["Tyrogue"],
  "HITMONTOP": ["Hitmontop"],
  "MILTANK": ["Miltank"],
  "RAIKOU": ["Raikou"],
  "ENTEI": ["Entei"],
  "SUICUNE": ["Suicune"],
  "LARVITAREVO": ["Larvitar", "Pupitar", "Tyranitar"],
  "LUGIA": ["Lugia"],
  "HOOH": ["Ho-oh"],
  "CELEBI": ["Celebi"],
  "TREECKOEVO": ["Treecko", "Grovyle", "Sceptile"],
  "TORCHICEVO": ["Torchic", "Combusken", "Blaziken"],
  "MUDKIPEVO": ["Mudkip", "Marshtomp", "Swampert"],
  "POOCHYENAEVO": ["Poochyena", "Mightyena"],
  "ZIGZAGOONEVO": ["Zigzagoon", "Linoone"],
  "WURMPLE": ["Wurmple"],
  "SILCOONEVO": ["Silcoon", "Beautifly"],
  "CASCOONEVO": ["Cascoon", "Dustox"],
  "LOTADEVO": ["Lotad", "Lombre", "Ludicolo"],
  "SEEDOTEVO": ["Seedot", "Nuzleaf", "Shiftry"],
  "TAILLOWEVO": ["Taillow", "Swellow"],
  "WINGULLEVO": ["Wingull", "Pelipper"],
  "RALTSEVO": ["Ralts", "Kirlia"],
  "GARDEVOIR": ["Gardevoir"],
  "SURSKITEVO": ["Surskit", "Masquerain"],
  "SHROOMISHEVO": ["Shroomish", "Breloom"],
  "SLAKOTHEVO": ["Slakoth", "Vigoroth", "Slaking"],
  "NINCADAEVO": ["Nincada", "Ninjask"],
  "SHEDINJA": ["Shedinja"],
  "WHISMUREVO": ["Whismur", "Loudred", "Exploud"],
  "MAKUHITAEVO": ["Makuhita", "Hariyama"],
  "NOSEPASSEVO": ["Nosepass"],
  "SKITTYEVO": ["Skitty", "Delcatty"],
  "SABLEYE": ["Sableye"],
  "MAWILE": ["Mawile"],
  "ARONEVO": ["Aron", "Lairon", "Aggron"],
  "MEDITITEEVO": ["Meditite", "Medicham"],
  "ELECTRIKEEVO": ["Electrike", "Manectric"],
  "PLUSLE": ["Plusle"],
  "MINUN": ["Minun"],
  "VOLBEAT": ["Volbeat"],
  "ILLUMISE": ["Illumise"],
  "BUDEWEVO": ["Roselia"],
  "GULPINEVO": ["Gulpin", "Swalot"],
  "CARVANHAEVO": ["Carvanha", "Sharpedo"],
  "WAILMEREVO": ["Wailmer", "Wailord"],
  "NUMELEVO": ["Numel", "Camerupt"],
  "TORKOAL": ["Torkoal"],
  "SPOINKEVO": ["Spoink", "Grumpig"],
  "SPINDA": ["Spinda"],
  "TRAPINCHEVO": ["Trapinch", "Vibrava", "Flygon"],
  "CACNEAEVO": ["Cacnea", "Cacturne"],
  "SWABLUEVO": ["Swablu", "Altaria"],
  "ZANGOOSE": ["Zangoose"],
  "SEVIPER": ["Seviper"],
  "LUNATONE": ["Lunatone"],
  "SOLROCK": ["Solrock"],
  "BARBOACHEVO": ["Barboach", "Whiscash"],
  "CORPISHEVO": ["Corphish", "Crawdaunt"],
  "BALTOYEVO": ["Baltoy", "Claydol"],
  "LILEEPEVO": ["Lileep", "Cradily"],
  "ANORITHEVO": ["Anorith", "Armaldo"],
  "FEEBAS": ["Feebas", "Milotic"],
  "CASTFORM": ["Castform"],
  "KECKLEON": ["Kecleon"],
  "SHUPPETEVO": ["Shuppet", "Banette"],
  "DUSKULLEVO": ["Duskull", "Dusclops"],
  "TROPIUS": ["Tropius"],
  "CHINGLINGEVO": ["Chimecho"],
  "ABSOL": ["Absol"],
  "SNORUNT": ["Snorunt"],
  "GLALIE": ["Glalie"],
  "SPHEALEVO": ["Spheal", "Sealeo", "Walrein"],
  "CLAMPERL": ["Clamperl"],
  "HUNTAIL": ["Huntail"],
  "GOREBYSS": ["Gorebyss"],
  "RELICANTH": ["Relicanth"],
  "LUVDISC": ["Luvdisc"],
  "BAGONEVO": ["Bagon", "Shelgon", "Salamence"],
  "BELDUMEVO": ["Beldum", "Metang", "Metagross"],
  "REGIROCK": ["Regirock"],
  "REGICE": ["Regice"],
  "REGISTEEL": ["Registeel"],
  "LATIAS": ["Latias"],
  "LATIOS": ["Latios"],
  "KYOGRE": ["Kyogre"],
  "GROUDON": ["Groudon"],
  "RAYQUAZA": ["Rayquaza"],
  "JIRACHI": ["Jirachi"],
  "DEOXYS": ["Deoxys"],
  "DEOXYSATTACK": ["Deoxys-attack"],
  "DEOXISDEFENSE": ["Deoxys-defense"],
  "DEOXYSSPEED": ["Deoxys-speed"],
}

export const EVOLUTIONS_GROUPS_4 = {
  "BULBASAUREVO": ["Bulbasaur", "Ivysaur", "Venusaur"],
  "CHARMANDEREVO": ["Charmander", "Charmeleon", "Charizard"],
  "SQUIRTLEVO": ["Squirtle", "Wartortle", "Blastoise"],
  "CATERPIEEVO": ["Caterpie", "Metapod", "Butterfree"],
  "WEEDLEEVO": ["Weedle", "Kakuna", "Beedrill"],
  "PIDGEYEVO": ["Pidgey", "Pidgeotto", "Pidgeot"],
  "RATTATAEVO": ["Rattata", "Raticate"],
  "SPEAROWEVO": ["Spearow", "Fearow"],
  "EKANSEVO": ["Ekans", "Arbok"],
  "PICHUEVO": ["Pichu", "Pikachu", "Raichu"],
  "SANDSHREWEVO": ["Sandshrew", "Sandslash"],
  "NIDORANFEVO": ["NidoranF", "Nidorina", "Nidoqueen"],
  "NIDORANMEVO": ["NidoranM", "Nidorino", "Nidoking"],
  "CLEFFAEVO": ["Cleffa", "Clefairy", "Clefable"],
  "VULPIXEVO": ["Vulpix", "Ninetales"],
  "IGGLYBUFFEVO": ["Igglybuff", "Jigglypuff", "Wigglytuff"],
  "ZUBATOEVO": ["Zubat", "Golbat", "Crobat"],
  "ODDISHEVO": ["Oddish", "Gloom"],
  "VILEPLUME": ["Vileplume"],
  "PARASEVO": ["Paras", "Parasect"],
  "VENONATEVO": ["Venonat", "Venomoth"],
  "DIGLETTEVO": ["Diglett", "Dugtrio"],
  "MEOWTHEVO": ["Meowth", "Persian"],
  "PSYDUCKEVO": ["Psyduck", "Golduck"],
  "MANKEYEVO": ["Mankey", "Primeape"],
  "GROWLITHEEVO": ["Growlithe", "Arcanine"],
  "POLIWAGEVO": ["Poliwag", "Poliwhirl"],
  "POLIWRATH": ["Poliwrath"],
  "ABRAEVO": ["Abra", "Kadabra", "Alakazam"],
  "MACHOPEVO": ["Machop", "Machoke", "Machamp"],
  "BELLSPROUTEVO": ["Bellsprout", "Weepinbell", "Victreebel"],
  "TENTACOOLEVO": ["Tentacool", "Tentacruel"],
  "GEODUDEEVO": ["Geodude", "Graveler", "Golem"],
  "PONYTAEVO": ["Ponyta", "Rapidash"],
  "SLOWPOKE": ["Slowpoke"],
  "SLOWBRO": ["Slowbro"],
  "MAGNEMITEEVO": ["Magnemite", "Magneton", "Magnezone"],
  "FARFECTHD": ["Farfetch'd"],
  "DODUOEVO": ["Doduo", "Dodrio"],
  "SEELEVO": ["Seel", "Dewgong"],
  "GRIMEREVO": ["Grimer", "Muk"],
  "SHELLDEREVO": ["Shellder", "Cloyster"],
  "GASTLYEVO": ["Gastly", "Haunter", "Gengar"],
  "ONIXEVO": ["Onix", "Steelix"],
  "DROWZEEEVO": ["Drowzee", "Hypno"],
  "KRABBYEVO": ["Krabby", "Kingler"],
  "VOLTORBEVO": ["Voltorb", "Electrode"],
  "EXEGGCUTEEVO": ["Exeggcute", "Exeggutor"],
  "CUBONEEVO": ["Cubone", "Marowak"],
  "HITMONLEE": ["Hitmonlee"],
  "HITMONCHAN": ["Hitmonchan"],
  "LICKYTUNGEVO": ["Lickitung", "Lickilicky"],
  "KOFFINGEVO": ["Koffing", "Weezing"],
  "RHYHORNEVO": ["Rhyhorn", "Rhydon", "Rhyperior"],
  "HAPPINYEVO": ["Happiny", "Chansey", "Blissey"],
  "TANGELAEVO": ["Tangela", "Tangrowth"],
  "KANGASKHAN": ["Kangaskhan"],
  "HORSEAEVO": ["Horsea", "Seadra", "Kingdra"],
  "GOLDEENEVO": ["Goldeen", "Seaking"],
  "STARYUEVO": ["Staryu", "Starmie"],
  "MIMEJREVO": ["Mime-jr", "Mr.Mime"],
  "SCYTHEREVO": ["Scyther", "Scizor"],
  "SMOOCHUMEVO": ["Smoochum", "Jynx"],
  "ELEKIDEVO": ["Elekid", "Electabuzz", "Electivire"],
  "MAGBYEVO": ["Magby", "Magmar", "Magmortar"],
  "PINSIR": ["Pinsir"],
  "TAUROS": ["Tauros"],
  "MAGKARPEVO": ["Magikarp", "Gyarados"],
  "LAPRAS": ["Lapras"],
  "DITTO": ["Ditto"],
  "EEVEE": ["Eevee"],
  "VAPOREON": ["Vaporeon"],
  "JOLTEON": ["Jolteon"],
  "FLAREON": ["Flareon"],
  "PORYGONEVO": ["Porygon", "Porygon2", "Porygon-Z"],
  "OMANYTEEVO": ["Omanyte", "Omastar"],
  "KABUTOEVO": ["Kabuto", "Kabutops"],
  "AERODACTYL": ["Aerodactyl"],
  "MUNCHLAXEVO": ["Munchlax", "Snorlax"],
  "ARTICUNO": ["Articuno"],
  "ZAPDOS": ["Zapdos"],
  "MOLTRES": ["Moltres"],
  "DRATINIEVO": ["Dratini", "Dragonair", "Dragonite"],
  "MEWTWO": ["Mewtwo"],
  "MEW": ["Mew"],
  "CHIKORITAEVO": ["Chikorita", "Bayleef", "Meganium"],
  "CYNDAQUILEVO": ["Cyndaquil", "Quilava", "Typhlosion"],
  "TOTODILEEVO": ["Totodile", "Croconaw", "Feraligatr"],
  "SENTRETEVO": ["Sentret", "Furret"],
  "HOOTHOOTEVO": ["Hoothoot", "Noctowl"],
  "LEDYBAEVO": ["Ledyba", "Ledian"],
  "SPINARAKEVO": ["Spinarak", "Ariados"],
  "CHINCHOUEVO": ["Chinchou", "Lanturn"],
  "TOGEPIEVO": ["Togepi", "Togetic", "Togekiss"],
  "NATUEVO": ["Natu", "Xatu"],
  "MAREEPEVO": ["Mareep", "Flaaffy", "Ampharos"],
  "BELLOSSOM": ["Bellossom"],
  "AZURILLEVO": ["Azurill", "Marill", "Azumarill"],
  "BONSLYEVO": ["Bonsly", "Sudowoodo"],
  "POLITOED": ["Politoed"],
  "HOPPIPEVO": ["Hoppip", "Skiploom", "Jumpluff"],
  "AIPOMEVO": ["Aipom", "Ambipom"],
  "SUNKERNEVO": ["Sunkern", "Sunflora"],
  "YANMAEVO": ["Yanma", "Yanmega"],
  "WOOPEREVO": ["Wooper", "Quagsire"],
  "ESPEON": ["Espeon"],
  "UMBREON": ["Umbreon"],
  "MURKROWEVO": ["Murkrow", "Honchkrow"],
  "SLOWKING": ["Slowking"],
  "MISDREAVUS": ["Misdreavus", "Mismagius"],
  "UNOWN": ["Unown"],
  "WYNAUTEVO": ["Wynaut", "Wobbuffet"],
  "GIRAFARIG": ["Girafarig"],
  "PINECOEVO": ["Pineco", "Forretress"],
  "DUNSPARCE": ["Dunsparce"],
  "GLIGAREVO": ["Gligar", "Gliscor"],
  "SNUBBULLEVO": ["Snubbull", "Granbull"],
  "QWILFISH": ["Qwilfish"],
  "SHUCKLE": ["Shuckle"],
  "HERACROSS": ["Heracross"],
  "SNEASELEVO": ["Sneasel", "Weavile"],
  "TEDDIURSAEVO": ["Teddiursa", "Ursaring"],
  "SLUGMAEVO": ["Slugma", "Magcargo"],
  "SWINUBEVO": ["Swinub", "Piloswine", "Mamoswine"],
  "CORSOLA": ["Corsola"],
  "REMORAIDEVO": ["Remoraid", "Octillery"],
  "DELIBIRD": ["Delibird"],
  "MANTYKEEVO": ["Mantyke", "Mantine"],
  "SKARMORY": ["Skarmory"],
  "HOUNDOUREVO": ["Houndour", "Houndoom"],
  "PHANPYEVO": ["Phanpy", "Donphan"],
  "STANTLER": ["Stantler"],
  "SMEARGLE": ["Smeargle"],
  "TYROGUE": ["Tyrogue"],
  "HITMONTOP": ["Hitmontop"],
  "MILTANK": ["Miltank"],
  "RAIKOU": ["Raikou"],
  "ENTEI": ["Entei"],
  "SUICUNE": ["Suicune"],
  "LARVITAREVO": ["Larvitar", "Pupitar", "Tyranitar"],
  "LUGIA": ["Lugia"],
  "HOOH": ["Ho-oh"],
  "CELEBI": ["Celebi"],
  "TREECKOEVO": ["Treecko", "Grovyle", "Sceptile"],
  "TORCHICEVO": ["Torchic", "Combusken", "Blaziken"],
  "MUDKIPEVO": ["Mudkip", "Marshtomp", "Swampert"],
  "POOCHYENAEVO": ["Poochyena", "Mightyena"],
  "ZIGZAGOONEVO": ["Zigzagoon", "Linoone"],
  "WURMPLE": ["Wurmple"],
  "SILCOONEVO": ["Silcoon", "Beautifly"],
  "CASCOONEVO": ["Cascoon", "Dustox"],
  "LOTADEVO": ["Lotad", "Lombre", "Ludicolo"],
  "SEEDOTEVO": ["Seedot", "Nuzleaf", "Shiftry"],
  "TAILLOWEVO": ["Taillow", "Swellow"],
  "WINGULLEVO": ["Wingull", "Pelipper"],
  "RALTSEVO": ["Ralts", "Kirlia"],
  "GARDEVOIR": ["Gardevoir"],
  "SURSKITEVO": ["Surskit", "Masquerain"],
  "SHROOMISHEVO": ["Shroomish", "Breloom"],
  "SLAKOTHEVO": ["Slakoth", "Vigoroth", "Slaking"],
  "NINCADAEVO": ["Nincada", "Ninjask"],
  "SHEDINJA": ["Shedinja"],
  "WHISMUREVO": ["Whismur", "Loudred", "Exploud"],
  "MAKUHITAEVO": ["Makuhita", "Hariyama"],
  "NOSEPASSEVO": ["Nosepass", "Probopass"],
  "SKITTYEVO": ["Skitty", "Delcatty"],
  "SABLEYE": ["Sableye"],
  "MAWILE": ["Mawile"],
  "ARONEVO": ["Aron", "Lairon", "Aggron"],
  "MEDITITEEVO": ["Meditite", "Medicham"],
  "ELECTRIKEEVO": ["Electrike", "Manectric"],
  "PLUSLE": ["Plusle"],
  "MINUN": ["Minun"],
  "VOLBEAT": ["Volbeat"],
  "ILLUMISE": ["Illumise"],
  "BUDEWEVO": ["Budew", "Roselia", "Roserade"],
  "GULPINEVO": ["Gulpin", "Swalot"],
  "CARVANHAEVO": ["Carvanha", "Sharpedo"],
  "WAILMEREVO": ["Wailmer", "Wailord"],
  "NUMELEVO": ["Numel", "Camerupt"],
  "TORKOAL": ["Torkoal"],
  "SPOINKEVO": ["Spoink", "Grumpig"],
  "SPINDA": ["Spinda"],
  "TRAPINCHEVO": ["Trapinch", "Vibrava", "Flygon"],
  "CACNEAEVO": ["Cacnea", "Cacturne"],
  "SWABLUEVO": ["Swablu", "Altaria"],
  "ZANGOOSE": ["Zangoose"],
  "SEVIPER": ["Seviper"],
  "LUNATONE": ["Lunatone"],
  "SOLROCK": ["Solrock"],
  "BARBOACHEVO": ["Barboach", "Whiscash"],
  "CORPISHEVO": ["Corphish", "Crawdaunt"],
  "BALTOYEVO": ["Baltoy", "Claydol"],
  "LILEEPEVO": ["Lileep", "Cradily"],
  "ANORITHEVO": ["Anorith", "Armaldo"],
  "FEEBAS": ["Feebas", "Milotic"],
  "CASTFORM": ["Castform"],
  "KECKLEON": ["Kecleon"],
  "SHUPPETEVO": ["Shuppet", "Banette"],
  "DUSKULLEVO": ["Duskull", "Dusclops", "Dusknoir"],
  "TROPIUS": ["Tropius"],
  "CHINGLINGEVO": ["Chingling", "Chimecho"],
  "ABSOL": ["Absol"],
  "SNORUNT": ["Snorunt"],
  "GLALIE": ["Glalie"],
  "SPHEALEVO": ["Spheal", "Sealeo", "Walrein"],
  "CLAMPERL": ["Clamperl"],
  "HUNTAIL": ["Huntail"],
  "GOREBYSS": ["Gorebyss"],
  "RELICANTH": ["Relicanth"],
  "LUVDISC": ["Luvdisc"],
  "BAGONEVO": ["Bagon", "Shelgon", "Salamence"],
  "BELDUMEVO": ["Beldum", "Metang", "Metagross"],
  "REGIROCK": ["Regirock"],
  "REGICE": ["Regice"],
  "REGISTEEL": ["Registeel"],
  "LATIAS": ["Latias"],
  "LATIOS": ["Latios"],
  "KYOGRE": ["Kyogre"],
  "GROUDON": ["Groudon"],
  "RAYQUAZA": ["Rayquaza"],
  "JIRACHI": ["Jirachi"],
  "DEOXYS": ["Deoxys"],
  "DEOXYSATTACK": ["Deoxys-attack"],
  "DEOXISDEFENSE": ["Deoxys-defense"],
  "DEOXYSSPEED": ["Deoxys-speed"],
  "TURTWIGEVO": ["Turtwig", "Grotle", "Torterra"],
  "CHIMCHAREVO": ["Chimchar", "Monferno", "Infernape"],
  "PIPLUPEVO": ["Piplup", "Prinplup", "Empoleon"],
  "STARLYEVO": ["Starly", "Staravia", "Staraptor"],
  "BIDOOFEVO": ["Bidoof", "Bibarel"],
  "KRICKETOTEVO": ["Kricketot", "Kricketune"],
  "SHINXEVO": ["Shinx", "Luxio", "Luxray"],
  "CRANIDOSEVO": ["Cranidos", "Rampardos"],
  "SHIELDONEVO": ["Shieldon", "Bastiodon"],
  "BURMY": ["Burmy"],
  "WORMADAMPLANT": ["Wormadam-plant"],
  "WORMADAMSANDY": ["Wormadam-sandy"],
  "WORMADAMTRASH": ["Wormadam-trash"],
  "MOTHIM": ["Mothim"],
  "COMBEEEVO": ["Combee", "Vespiquen"],
  "PACHIRISU": ["Pachirisu"],
  "BUIZELEVO": ["Buizel", "Floatzel"],
  "CHERUBIEVO": ["Cherubi", "Cherrim"],
  "SHELLOSEVO": ["Shellos", "Gastrodon"],
  "DRIFLOONEVO": ["Drifloon", "Drifblim"],
  "BUNEARYEVO": ["Buneary", "Lopunny"],
  "GLAMEOWEVO": ["Glameow", "Purugly"],
  "STUNKYEVO": ["Stunky", "Skuntank"],
  "BRONZOREVO": ["Bronzor", "Bronzong"],
  "CHATOT": ["Chatot"],
  "SPIRITOMB": ["Spiritomb"],
  "GIBLEEVO": ["Gible", "Gabite", "Garchomp"],
  "RIOLUEVO": ["Riolu", "Lucario"],
  "HIPPOPOTASEVO": ["Hippopotas", "Hippowdon"],
  "SKORUPIEVO": ["Skorupi", "Drapion"],
  "CROAGUNKEVO": ["Croagunk", "Toxicroak"],
  "CARNIVINE": ["Carnivine"],
  "FINNEONEVO": ["Finneon", "Lumineon"],
  "SNOVEREVO": ["Snover", "Abomasnow"],
  "LEAFEON": ["Leafeon"],
  "GLACEON": ["Glaceon"],
  "GALLADE": ["Gallade"],
  "FROSLASS": ["Froslass"],
  "ROTOM": ["Rotom"],
  "ROTOMHEAT": ["Rotom-heat"],
  "ROTOMWASH": ["Rotom-wash"],
  "ROTOMFROST": ["Rotom-frost"],
  "ROTOMFAN": ["Rotom-fan"],
  "ROTOMMOW": ["Rotom-mow"],
  "UXIE": ["Uxie"],
  "MESPRIT": ["Mesprit"],
  "AZELF": ["Azelf"],
  "DIALGA": ["Dialga"],
  "PALKIA": ["Palkia"],
  "HEATRAN": ["Heatran"],
  "REGIGIGAS": ["Regigigas"],
  "GIRATINAALTERED": ["Giratina-altered"],
  "GIRATINAORIGIN": ["Giratina-origin"],
  "CRESSELIA": ["Cresselia"],
  "PHIONE": ["Phione"],
  "MANAPHY": ["Manaphy"],
  "DARKRAI": ["Darkrai"],
  "SHAYMINLAND": ["Shaymin-land"],
  "SHAYMINSKY": ["Shaymin-sky"],
  "ARCEUS": ["Arceus"]
}

export const EVOLUTIONS_GROUPS = {
  "BULBASAUREVO": ["Bulbasaur", "Ivysaur", "Venusaur"],
  "CHARMANDEREVO": ["Charmander", "Charmeleon", "Charizard"],
  "SQUIRTLEVO": ["Squirtle", "Wartortle", "Blastoise"],
  "CATERPIEEVO": ["Caterpie", "Metapod", "Butterfree"],
  "WEEDLEEVO": ["Weedle", "Kakuna", "Beedrill"],
  "PIDGEYEVO": ["Pidgey", "Pidgeotto", "Pidgeot"],
  "RATTATAEVO": ["Rattata", "Raticate"],
  "SPEAROWEVO": ["Spearow", "Fearow"],
  "EKANSEVO": ["Ekans", "Arbok"],
  "PICHUEVO": ["Pichu", "Pikachu", "Raichu"],
  "SANDSHREWEVO": ["Sandshrew", "Sandslash"],
  "NIDORANFEVO": ["NidoranF", "Nidorina", "Nidoqueen"],
  "NIDORANMEVO": ["NidoranM", "Nidorino", "Nidoking"],
  "CLEFFAEVO": ["Cleffa", "Clefairy", "Clefable"],
  "VULPIXEVO": ["Vulpix", "Ninetales"],
  "IGGLYBUFFEVO": ["Igglybuff", "Jigglypuff", "Wigglytuff"],
  "ZUBATOEVO": ["Zubat", "Golbat", "Crobat"],
  "ODDISHEVO": ["Oddish", "Gloom"],
  "VILEPLUME": ["Vileplume"],
  "PARASEVO": ["Paras", "Parasect"],
  "VENONATEVO": ["Venonat", "Venomoth"],
  "DIGLETTEVO": ["Diglett", "Dugtrio"],
  "MEOWTHEVO": ["Meowth", "Persian"],
  "PSYDUCKEVO": ["Psyduck", "Golduck"],
  "MANKEYEVO": ["Mankey", "Primeape"],
  "GROWLITHEEVO": ["Growlithe", "Arcanine"],
  "POLIWAGEVO": ["Poliwag", "Poliwhirl"],
  "POLIWRATH": ["Poliwrath"],
  "ABRAEVO": ["Abra", "Kadabra", "Alakazam"],
  "MACHOPEVO": ["Machop", "Machoke", "Machamp"],
  "BELLSPROUTEVO": ["Bellsprout", "Weepinbell", "Victreebel"],
  "TENTACOOLEVO": ["Tentacool", "Tentacruel"],
  "GEODUDEEVO": ["Geodude", "Graveler", "Golem"],
  "PONYTAEVO": ["Ponyta", "Rapidash"],
  "SLOWPOKE": ["Slowpoke"],
  "SLOWBRO": ["Slowbro"],
  "MAGNEMITEEVO": ["Magnemite", "Magneton", "Magnezone"],
  "FARFECTHD": ["Farfetch'd"],
  "DODUOEVO": ["Doduo", "Dodrio"],
  "SEELEVO": ["Seel", "Dewgong"],
  "GRIMEREVO": ["Grimer", "Muk"],
  "SHELLDEREVO": ["Shellder", "Cloyster"],
  "GASTLYEVO": ["Gastly", "Haunter", "Gengar"],
  "ONIXEVO": ["Onix", "Steelix"],
  "DROWZEEEVO": ["Drowzee", "Hypno"],
  "KRABBYEVO": ["Krabby", "Kingler"],
  "VOLTORBEVO": ["Voltorb", "Electrode"],
  "EXEGGCUTEEVO": ["Exeggcute", "Exeggutor"],
  "CUBONEEVO": ["Cubone", "Marowak"],
  "HITMONLEE": ["Hitmonlee"],
  "HITMONCHAN": ["Hitmonchan"],
  "LICKYTUNGEVO": ["Lickitung", "Lickilicky"],
  "KOFFINGEVO": ["Koffing", "Weezing"],
  "RHYHORNEVO": ["Rhyhorn", "Rhydon", "Rhyperior"],
  "HAPPINYEVO": ["Happiny", "Chansey", "Blissey"],
  "TANGELAEVO": ["Tangela", "Tangrowth"],
  "KANGASKHAN": ["Kangaskhan"],
  "HORSEAEVO": ["Horsea", "Seadra", "Kingdra"],
  "GOLDEENEVO": ["Goldeen", "Seaking"],
  "STARYUEVO": ["Staryu", "Starmie"],
  "MIMEJREVO": ["Mime-jr", "Mr.Mime"],
  "SCYTHEREVO": ["Scyther", "Scizor"],
  "SMOOCHUMEVO": ["Smoochum", "Jynx"],
  "ELEKIDEVO": ["Elekid", "Electabuzz", "Electivire"],
  "MAGBYEVO": ["Magby", "Magmar", "Magmortar"],
  "PINSIR": ["Pinsir"],
  "TAUROS": ["Tauros"],
  "MAGKARPEVO": ["Magikarp", "Gyarados"],
  "LAPRAS": ["Lapras"],
  "DITTO": ["Ditto"],
  "EEVEE": ["Eevee"],
  "VAPOREON": ["Vaporeon"],
  "JOLTEON": ["Jolteon"],
  "FLAREON": ["Flareon"],
  "PORYGONEVO": ["Porygon", "Porygon2", "Porygon-Z"],
  "OMANYTEEVO": ["Omanyte", "Omastar"],
  "KABUTOEVO": ["Kabuto", "Kabutops"],
  "AERODACTYL": ["Aerodactyl"],
  "MUNCHLAXEVO": ["Munchlax", "Snorlax"],
  "ARTICUNO": ["Articuno"],
  "ZAPDOS": ["Zapdos"],
  "MOLTRES": ["Moltres"],
  "DRATINIEVO": ["Dratini", "Dragonair", "Dragonite"],
  "MEWTWO": ["Mewtwo"],
  "MEW": ["Mew"],
  "CHIKORITAEVO": ["Chikorita", "Bayleef", "Meganium"],
  "CYNDAQUILEVO": ["Cyndaquil", "Quilava", "Typhlosion"],
  "TOTODILEEVO": ["Totodile", "Croconaw", "Feraligatr"],
  "SENTRETEVO": ["Sentret", "Furret"],
  "HOOTHOOTEVO": ["Hoothoot", "Noctowl"],
  "LEDYBAEVO": ["Ledyba", "Ledian"],
  "SPINARAKEVO": ["Spinarak", "Ariados"],
  "CHINCHOUEVO": ["Chinchou", "Lanturn"],
  "TOGEPIEVO": ["Togepi", "Togetic", "Togekiss"],
  "NATUEVO": ["Natu", "Xatu"],
  "MAREEPEVO": ["Mareep", "Flaaffy", "Ampharos"],
  "BELLOSSOM": ["Bellossom"],
  "AZURILLEVO": ["Azurill", "Marill", "Azumarill"],
  "BONSLYEVO": ["Bonsly", "Sudowoodo"],
  "POLITOED": ["Politoed"],
  "HOPPIPEVO": ["Hoppip", "Skiploom", "Jumpluff"],
  "AIPOMEVO": ["Aipom", "Ambipom"],
  "SUNKERNEVO": ["Sunkern", "Sunflora"],
  "YANMAEVO": ["Yanma", "Yanmega"],
  "WOOPEREVO": ["Wooper", "Quagsire"],
  "ESPEON": ["Espeon"],
  "UMBREON": ["Umbreon"],
  "MURKROWEVO": ["Murkrow", "Honchkrow"],
  "SLOWKING": ["Slowking"],
  "MISDREAVUS": ["Misdreavus", "Mismagius"],
  "UNOWN": ["Unown"],
  "WYNAUTEVO": ["Wynaut", "Wobbuffet"],
  "GIRAFARIG": ["Girafarig"],
  "PINECOEVO": ["Pineco", "Forretress"],
  "DUNSPARCE": ["Dunsparce"],
  "GLIGAREVO": ["Gligar", "Gliscor"],
  "SNUBBULLEVO": ["Snubbull", "Granbull"],
  "QWILFISH": ["Qwilfish"],
  "SHUCKLE": ["Shuckle"],
  "HERACROSS": ["Heracross"],
  "SNEASELEVO": ["Sneasel", "Weavile"],
  "TEDDIURSAEVO": ["Teddiursa", "Ursaring"],
  "SLUGMAEVO": ["Slugma", "Magcargo"],
  "SWINUBEVO": ["Swinub", "Piloswine", "Mamoswine"],
  "CORSOLA": ["Corsola"],
  "REMORAIDEVO": ["Remoraid", "Octillery"],
  "DELIBIRD": ["Delibird"],
  "MANTYKEEVO": ["Mantyke", "Mantine"],
  "SKARMORY": ["Skarmory"],
  "HOUNDOUREVO": ["Houndour", "Houndoom"],
  "PHANPYEVO": ["Phanpy", "Donphan"],
  "STANTLER": ["Stantler"],
  "SMEARGLE": ["Smeargle"],
  "TYROGUE": ["Tyrogue"],
  "HITMONTOP": ["Hitmontop"],
  "MILTANK": ["Miltank"],
  "RAIKOU": ["Raikou"],
  "ENTEI": ["Entei"],
  "SUICUNE": ["Suicune"],
  "LARVITAREVO": ["Larvitar", "Pupitar", "Tyranitar"],
  "LUGIA": ["Lugia"],
  "HOOH": ["Ho-oh"],
  "CELEBI": ["Celebi"],
  "TREECKOEVO": ["Treecko", "Grovyle", "Sceptile"],
  "TORCHICEVO": ["Torchic", "Combusken", "Blaziken"],
  "MUDKIPEVO": ["Mudkip", "Marshtomp", "Swampert"],
  "POOCHYENAEVO": ["Poochyena", "Mightyena"],
  "ZIGZAGOONEVO": ["Zigzagoon", "Linoone"],
  "WURMPLE": ["Wurmple"],
  "SILCOONEVO": ["Silcoon", "Beautifly"],
  "CASCOONEVO": ["Cascoon", "Dustox"],
  "LOTADEVO": ["Lotad", "Lombre", "Ludicolo"],
  "SEEDOTEVO": ["Seedot", "Nuzleaf", "Shiftry"],
  "TAILLOWEVO": ["Taillow", "Swellow"],
  "WINGULLEVO": ["Wingull", "Pelipper"],
  "RALTSEVO": ["Ralts", "Kirlia"],
  "GARDEVOIR": ["Gardevoir"],
  "SURSKITEVO": ["Surskit", "Masquerain"],
  "SHROOMISHEVO": ["Shroomish", "Breloom"],
  "SLAKOTHEVO": ["Slakoth", "Vigoroth", "Slaking"],
  "NINCADAEVO": ["Nincada", "Ninjask"],
  "SHEDINJA": ["Shedinja"],
  "WHISMUREVO": ["Whismur", "Loudred", "Exploud"],
  "MAKUHITAEVO": ["Makuhita", "Hariyama"],
  "NOSEPASSEVO": ["Nosepass", "Probopass"],
  "SKITTYEVO": ["Skitty", "Delcatty"],
  "SABLEYE": ["Sableye"],
  "MAWILE": ["Mawile"],
  "ARONEVO": ["Aron", "Lairon", "Aggron"],
  "MEDITITEEVO": ["Meditite", "Medicham"],
  "ELECTRIKEEVO": ["Electrike", "Manectric"],
  "PLUSLE": ["Plusle"],
  "MINUN": ["Minun"],
  "VOLBEAT": ["Volbeat"],
  "ILLUMISE": ["Illumise"],
  "BUDEWEVO": ["Budew", "Roselia", "Roserade"],
  "GULPINEVO": ["Gulpin", "Swalot"],
  "CARVANHAEVO": ["Carvanha", "Sharpedo"],
  "WAILMEREVO": ["Wailmer", "Wailord"],
  "NUMELEVO": ["Numel", "Camerupt"],
  "TORKOAL": ["Torkoal"],
  "SPOINKEVO": ["Spoink", "Grumpig"],
  "SPINDA": ["Spinda"],
  "TRAPINCHEVO": ["Trapinch", "Vibrava", "Flygon"],
  "CACNEAEVO": ["Cacnea", "Cacturne"],
  "SWABLUEVO": ["Swablu", "Altaria"],
  "ZANGOOSE": ["Zangoose"],
  "SEVIPER": ["Seviper"],
  "LUNATONE": ["Lunatone"],
  "SOLROCK": ["Solrock"],
  "BARBOACHEVO": ["Barboach", "Whiscash"],
  "CORPISHEVO": ["Corphish", "Crawdaunt"],
  "BALTOYEVO": ["Baltoy", "Claydol"],
  "LILEEPEVO": ["Lileep", "Cradily"],
  "ANORITHEVO": ["Anorith", "Armaldo"],
  "FEEBAS": ["Feebas", "Milotic"],
  "CASTFORM": ["Castform"],
  "KECKLEON": ["Kecleon"],
  "SHUPPETEVO": ["Shuppet", "Banette"],
  "DUSKULLEVO": ["Duskull", "Dusclops", "Dusknoir"],
  "TROPIUS": ["Tropius"],
  "CHINGLINGEVO": ["Chingling", "Chimecho"],
  "ABSOL": ["Absol"],
  "SNORUNT": ["Snorunt"],
  "GLALIE": ["Glalie"],
  "SPHEALEVO": ["Spheal", "Sealeo", "Walrein"],
  "CLAMPERL": ["Clamperl"],
  "HUNTAIL": ["Huntail"],
  "GOREBYSS": ["Gorebyss"],
  "RELICANTH": ["Relicanth"],
  "LUVDISC": ["Luvdisc"],
  "BAGONEVO": ["Bagon", "Shelgon", "Salamence"],
  "BELDUMEVO": ["Beldum", "Metang", "Metagross"],
  "REGIROCK": ["Regirock"],
  "REGICE": ["Regice"],
  "REGISTEEL": ["Registeel"],
  "LATIAS": ["Latias"],
  "LATIOS": ["Latios"],
  "KYOGRE": ["Kyogre"],
  "GROUDON": ["Groudon"],
  "RAYQUAZA": ["Rayquaza"],
  "JIRACHI": ["Jirachi"],
  "DEOXYS": ["Deoxys"],
  "DEOXYSATTACK": ["Deoxys-attack"],
  "DEOXISDEFENSE": ["Deoxys-defense"],
  "DEOXYSSPEED": ["Deoxys-speed"],
  "TURTWIGEVO": ["Turtwig", "Grotle", "Torterra"],
  "CHIMCHAREVO": ["Chimchar", "Monferno", "Infernape"],
  "PIPLUPEVO": ["Piplup", "Prinplup", "Empoleon"],
  "STARLYEVO": ["Starly", "Staravia", "Staraptor"],
  "BIDOOFEVO": ["Bidoof", "Bibarel"],
  "KRICKETOTEVO": ["Kricketot", "Kricketune"],
  "SHINXEVO": ["Shinx", "Luxio", "Luxray"],
  "CRANIDOSEVO": ["Cranidos", "Rampardos"],
  "SHIELDONEVO": ["Shieldon", "Bastiodon"],
  "BURMY": ["Burmy"],
  "WORMADAMPLANT": ["Wormadam-plant"],
  "WORMADAMSANDY": ["Wormadam-sandy"],
  "WORMADAMTRASH": ["Wormadam-trash"],
  "MOTHIM": ["Mothim"],
  "COMBEEEVO": ["Combee", "Vespiquen"],
  "PACHIRISU": ["Pachirisu"],
  "BUIZELEVO": ["Buizel", "Floatzel"],
  "CHERUBIEVO": ["Cherubi", "Cherrim"],
  "SHELLOSEVO": ["Shellos", "Gastrodon"],
  "DRIFLOONEVO": ["Drifloon", "Drifblim"],
  "BUNEARYEVO": ["Buneary", "Lopunny"],
  "GLAMEOWEVO": ["Glameow", "Purugly"],
  "STUNKYEVO": ["Stunky", "Skuntank"],
  "BRONZOREVO": ["Bronzor", "Bronzong"],
  "CHATOT": ["Chatot"],
  "SPIRITOMB": ["Spiritomb"],
  "GIBLEEVO": ["Gible", "Gabite", "Garchomp"],
  "RIOLUEVO": ["Riolu", "Lucario"],
  "HIPPOPOTASEVO": ["Hippopotas", "Hippowdon"],
  "SKORUPIEVO": ["Skorupi", "Drapion"],
  "CROAGUNKEVO": ["Croagunk", "Toxicroak"],
  "CARNIVINE": ["Carnivine"],
  "FINNEONEVO": ["Finneon", "Lumineon"],
  "SNOVEREVO": ["Snover", "Abomasnow"],
  "LEAFEON": ["Leafeon"],
  "GLACEON": ["Glaceon"],
  "GALLADE": ["Gallade"],
  "FROSLASS": ["Froslass"],
  "ROTOM": ["Rotom"],
  "ROTOMHEAT": ["Rotom-heat"],
  "ROTOMWASH": ["Rotom-wash"],
  "ROTOMFROST": ["Rotom-frost"],
  "ROTOMFAN": ["Rotom-fan"],
  "ROTOMMOW": ["Rotom-mow"],
  "UXIE": ["Uxie"],
  "MESPRIT": ["Mesprit"],
  "AZELF": ["Azelf"],
  "DIALGA": ["Dialga"],
  "PALKIA": ["Palkia"],
  "HEATRAN": ["Heatran"],
  "REGIGIGAS": ["Regigigas"],
  "GIRATINAALTERED": ["Giratina-altered"],
  "GIRATINAORIGIN": ["Giratina-origin"],
  "CRESSELIA": ["Cresselia"],
  "PHIONE": ["Phione"],
  "MANAPHY": ["Manaphy"],
  "DARKRAI": ["Darkrai"],
  "SHAYMINLAND": ["Shaymin-land"],
  "SHAYMINSKY": ["Shaymin-sky"],
  "ARCEUS": ["Arceus"]
}

export const POKEMON_EVOS: Record<string, string[]> = {
  "Bulbasaur": EVOLUTIONS_GROUPS.BULBASAUREVO,
  "Ivysaur": EVOLUTIONS_GROUPS.BULBASAUREVO,
  "Venusaur": EVOLUTIONS_GROUPS.BULBASAUREVO,
  "Charmander": EVOLUTIONS_GROUPS.CHARMANDEREVO,
  "Charmeleon": EVOLUTIONS_GROUPS.CHARMANDEREVO,
  "Charizard": EVOLUTIONS_GROUPS.CHARMANDEREVO,
  "Squirtle": EVOLUTIONS_GROUPS.SQUIRTLEVO,
  "Wartortle": EVOLUTIONS_GROUPS.SQUIRTLEVO,
  "Blastoise": EVOLUTIONS_GROUPS.SQUIRTLEVO,
  "Caterpie": EVOLUTIONS_GROUPS.CATERPIEEVO,
  "Metapod": EVOLUTIONS_GROUPS.CATERPIEEVO,
  "Butterfree": EVOLUTIONS_GROUPS.CATERPIEEVO,
  "Weedle": EVOLUTIONS_GROUPS.WEEDLEEVO,
  "Kakuna": EVOLUTIONS_GROUPS.WEEDLEEVO,
  "Beedrill": EVOLUTIONS_GROUPS.WEEDLEEVO,
  "Pidgey": EVOLUTIONS_GROUPS.PIDGEYEVO,
  "Pidgeotto": EVOLUTIONS_GROUPS.PIDGEYEVO,
  "Pidgeot": EVOLUTIONS_GROUPS.PIDGEYEVO,
  "Rattata": EVOLUTIONS_GROUPS.RATTATAEVO,
  "Raticate": EVOLUTIONS_GROUPS.RATTATAEVO,
  "Spearow": EVOLUTIONS_GROUPS.SPEAROWEVO,
  "Fearow": EVOLUTIONS_GROUPS.SPEAROWEVO,
  "Ekans": EVOLUTIONS_GROUPS.EKANSEVO,
  "Arbok": EVOLUTIONS_GROUPS.EKANSEVO,
  "Pikachu": EVOLUTIONS_GROUPS.PICHUEVO,
  "Raichu": EVOLUTIONS_GROUPS.PICHUEVO,
  "Sandshrew": EVOLUTIONS_GROUPS.SANDSHREWEVO,
  "Sandslash": EVOLUTIONS_GROUPS.SANDSHREWEVO,
  "NidoranF": EVOLUTIONS_GROUPS.NIDORANFEVO,
  "Nidorina": EVOLUTIONS_GROUPS.NIDORANFEVO,
  "Nidoqueen": EVOLUTIONS_GROUPS.NIDORANFEVO,
  "NidoranM": EVOLUTIONS_GROUPS.NIDORANMEVO,
  "Nidorino": EVOLUTIONS_GROUPS.NIDORANMEVO,
  "Nidoking": EVOLUTIONS_GROUPS.NIDORANMEVO,
  "Clefairy": EVOLUTIONS_GROUPS.CLEFFAEVO,
  "Clefable": EVOLUTIONS_GROUPS.CLEFFAEVO,
  "Vulpix": EVOLUTIONS_GROUPS.VULPIXEVO,
  "Ninetales": EVOLUTIONS_GROUPS.VULPIXEVO,
  "Jigglypuff": EVOLUTIONS_GROUPS.IGGLYBUFFEVO,
  "Wigglytuff": EVOLUTIONS_GROUPS.IGGLYBUFFEVO,
  "Zubat": EVOLUTIONS_GROUPS.ZUBATOEVO,
  "Golbat": EVOLUTIONS_GROUPS.ZUBATOEVO,
  "Oddish": EVOLUTIONS_GROUPS.ODDISHEVO,
  "Gloom": EVOLUTIONS_GROUPS.ODDISHEVO,
  "Vileplume": EVOLUTIONS_GROUPS.VILEPLUME,
  "Paras": EVOLUTIONS_GROUPS.PARASEVO,
  "Parasect": EVOLUTIONS_GROUPS.PARASEVO,
  "Venonat": EVOLUTIONS_GROUPS.VENONATEVO,
  "Venomoth": EVOLUTIONS_GROUPS.VENONATEVO,
  "Diglett": EVOLUTIONS_GROUPS.DIGLETTEVO,
  "Dugtrio": EVOLUTIONS_GROUPS.DIGLETTEVO,
  "Meowth": EVOLUTIONS_GROUPS.MEOWTHEVO,
  "Persian": EVOLUTIONS_GROUPS.MEOWTHEVO,
  "Psyduck": EVOLUTIONS_GROUPS.PSYDUCKEVO,
  "Golduck": EVOLUTIONS_GROUPS.PSYDUCKEVO,
  "Mankey": EVOLUTIONS_GROUPS.MANKEYEVO,
  "Primeape": EVOLUTIONS_GROUPS.MANKEYEVO,
  "Growlithe": EVOLUTIONS_GROUPS.GROWLITHEEVO,
  "Arcanine": EVOLUTIONS_GROUPS.GROWLITHEEVO,
  "Poliwag": EVOLUTIONS_GROUPS.POLIWAGEVO,
  "Poliwhirl": EVOLUTIONS_GROUPS.POLIWAGEVO,
  "Poliwrath": EVOLUTIONS_GROUPS.POLIWRATH,
  "Abra": EVOLUTIONS_GROUPS.ABRAEVO,
  "Kadabra": EVOLUTIONS_GROUPS.ABRAEVO,
  "Alakazam": EVOLUTIONS_GROUPS.ABRAEVO,
  "Machop": EVOLUTIONS_GROUPS.MACHOPEVO,
  "Machoke": EVOLUTIONS_GROUPS.MACHOPEVO,
  "Machamp": EVOLUTIONS_GROUPS.MACHOPEVO,
  "Bellsprout": EVOLUTIONS_GROUPS.BELLSPROUTEVO,
  "Weepinbell": EVOLUTIONS_GROUPS.BELLSPROUTEVO,
  "Victreebel": EVOLUTIONS_GROUPS.BELLSPROUTEVO,
  "Tentacool": EVOLUTIONS_GROUPS.TENTACOOLEVO,
  "Tentacruel": EVOLUTIONS_GROUPS.TENTACOOLEVO,
  "Geodude": EVOLUTIONS_GROUPS.GEODUDEEVO,
  "Graveler": EVOLUTIONS_GROUPS.GEODUDEEVO,
  "Golem": EVOLUTIONS_GROUPS.GEODUDEEVO,
  "Ponyta": EVOLUTIONS_GROUPS.PONYTAEVO,
  "Rapidash": EVOLUTIONS_GROUPS.PONYTAEVO,
  "Slowpoke": EVOLUTIONS_GROUPS.SLOWPOKE,
  "Slowbro": EVOLUTIONS_GROUPS.SLOWBRO,
  "Magnemite": EVOLUTIONS_GROUPS.MAGNEMITEEVO,
  "Magneton": EVOLUTIONS_GROUPS.MAGNEMITEEVO,
  "Farfetch'd": EVOLUTIONS_GROUPS.FARFECTHD,
  "Doduo": EVOLUTIONS_GROUPS.DODUOEVO,
  "Dodrio": EVOLUTIONS_GROUPS.DODUOEVO,
  "Seel": EVOLUTIONS_GROUPS.SEELEVO,
  "Dewgong": EVOLUTIONS_GROUPS.SEELEVO,
  "Grimer": EVOLUTIONS_GROUPS.GRIMEREVO,
  "Muk": EVOLUTIONS_GROUPS.GRIMEREVO,
  "Shellder": EVOLUTIONS_GROUPS.SHELLDEREVO,
  "Cloyster": EVOLUTIONS_GROUPS.SHELLDEREVO,
  "Gastly": EVOLUTIONS_GROUPS.GASTLYEVO,
  "Haunter": EVOLUTIONS_GROUPS.GASTLYEVO,
  "Gengar": EVOLUTIONS_GROUPS.GASTLYEVO,
  "Onix": EVOLUTIONS_GROUPS.ONIXEVO,
  "Drowzee": EVOLUTIONS_GROUPS.DROWZEEEVO,
  "Hypno": EVOLUTIONS_GROUPS.DROWZEEEVO,
  "Krabby": EVOLUTIONS_GROUPS.KRABBYEVO,
  "Kingler": EVOLUTIONS_GROUPS.KRABBYEVO,
  "Voltorb": EVOLUTIONS_GROUPS.VOLTORBEVO,
  "Electrode": EVOLUTIONS_GROUPS.VOLTORBEVO,
  "Exeggcute": EVOLUTIONS_GROUPS.EXEGGCUTEEVO,
  "Exeggutor": EVOLUTIONS_GROUPS.EXEGGCUTEEVO,
  "Cubone": EVOLUTIONS_GROUPS.CUBONEEVO,
  "Marowak": EVOLUTIONS_GROUPS.CUBONEEVO,
  "Hitmonlee": EVOLUTIONS_GROUPS.HITMONLEE,
  "Hitmonchan": EVOLUTIONS_GROUPS.HITMONCHAN,
  "Lickitung": EVOLUTIONS_GROUPS.LICKYTUNGEVO,
  "Koffing": EVOLUTIONS_GROUPS.KOFFINGEVO,
  "Weezing": EVOLUTIONS_GROUPS.KOFFINGEVO,
  "Rhyhorn": EVOLUTIONS_GROUPS.RHYHORNEVO,
  "Rhydon": EVOLUTIONS_GROUPS.RHYHORNEVO,
  "Chansey": EVOLUTIONS_GROUPS.HAPPINYEVO,
  "Tangela": EVOLUTIONS_GROUPS.TANGELAEVO,
  "Kangaskhan": EVOLUTIONS_GROUPS.KANGASKHAN,
  "Horsea": EVOLUTIONS_GROUPS.HORSEAEVO,
  "Seadra": EVOLUTIONS_GROUPS.HORSEAEVO,
  "Goldeen": EVOLUTIONS_GROUPS.GOLDEENEVO,
  "Seaking": EVOLUTIONS_GROUPS.GOLDEENEVO,
  "Staryu": EVOLUTIONS_GROUPS.STARYUEVO,
  "Starmie": EVOLUTIONS_GROUPS.STARYUEVO,
  "Mr.Mime": EVOLUTIONS_GROUPS.MIMEJREVO,
  "Scyther": EVOLUTIONS_GROUPS.SCYTHEREVO,
  "Jynx": EVOLUTIONS_GROUPS.SMOOCHUMEVO,
  "Electabuzz": EVOLUTIONS_GROUPS.ELEKIDEVO,
  "Magmar": EVOLUTIONS_GROUPS.MAGBYEVO,
  "Pinsir": EVOLUTIONS_GROUPS.PINSIR,
  "Tauros": EVOLUTIONS_GROUPS.TAUROS,
  "Magikarp": EVOLUTIONS_GROUPS.MAGKARPEVO,
  "Gyarados": EVOLUTIONS_GROUPS.MAGKARPEVO,
  "Lapras": EVOLUTIONS_GROUPS.LAPRAS,
  "Ditto": EVOLUTIONS_GROUPS.DITTO,
  "Eevee": EVOLUTIONS_GROUPS.EEVEE,
  "Vaporeon": EVOLUTIONS_GROUPS.VAPOREON,
  "Jolteon": EVOLUTIONS_GROUPS.JOLTEON,
  "Flareon": EVOLUTIONS_GROUPS.FLAREON,
  "Porygon": EVOLUTIONS_GROUPS.PORYGONEVO,
  "Omanyte": EVOLUTIONS_GROUPS.OMANYTEEVO,
  "Omastar": EVOLUTIONS_GROUPS.OMANYTEEVO,
  "Kabuto": EVOLUTIONS_GROUPS.KABUTOEVO,
  "Kabutops": EVOLUTIONS_GROUPS.KABUTOEVO,
  "Aerodactyl": EVOLUTIONS_GROUPS.AERODACTYL,
  "Snorlax": EVOLUTIONS_GROUPS.MUNCHLAXEVO,
  "Articuno": EVOLUTIONS_GROUPS.ARTICUNO,
  "Zapdos": EVOLUTIONS_GROUPS.ZAPDOS,
  "Moltres": EVOLUTIONS_GROUPS.MOLTRES,
  "Dratini": EVOLUTIONS_GROUPS.DRATINIEVO,
  "Dragonair": EVOLUTIONS_GROUPS.DRATINIEVO,
  "Dragonite": EVOLUTIONS_GROUPS.DRATINIEVO,
  "Mewtwo": EVOLUTIONS_GROUPS.MEWTWO,
  "Mew": EVOLUTIONS_GROUPS.MEW,
  "Chikorita": EVOLUTIONS_GROUPS.CHIKORITAEVO,
  "Bayleef": EVOLUTIONS_GROUPS.CHIKORITAEVO,
  "Meganium": EVOLUTIONS_GROUPS.CHIKORITAEVO,
  "Cyndaquil": EVOLUTIONS_GROUPS.CYNDAQUILEVO,
  "Quilava": EVOLUTIONS_GROUPS.CYNDAQUILEVO,
  "Typhlosion": EVOLUTIONS_GROUPS.CYNDAQUILEVO,
  "Totodile": EVOLUTIONS_GROUPS.TOTODILEEVO,
  "Croconaw": EVOLUTIONS_GROUPS.TOTODILEEVO,
  "Feraligatr": EVOLUTIONS_GROUPS.TOTODILEEVO,
  "Sentret": EVOLUTIONS_GROUPS.SENTRETEVO,
  "Furret": EVOLUTIONS_GROUPS.SENTRETEVO,
  "Hoothoot": EVOLUTIONS_GROUPS.HOOTHOOTEVO,
  "Noctowl": EVOLUTIONS_GROUPS.HOOTHOOTEVO,
  "Ledyba": EVOLUTIONS_GROUPS.LEDYBAEVO,
  "Ledian": EVOLUTIONS_GROUPS.LEDYBAEVO,
  "Spinarak": EVOLUTIONS_GROUPS.SPINARAKEVO,
  "Ariados": EVOLUTIONS_GROUPS.SPINARAKEVO,
  "Crobat": EVOLUTIONS_GROUPS.ZUBATOEVO,
  "Chinchou": EVOLUTIONS_GROUPS.CHINCHOUEVO,
  "Lanturn": EVOLUTIONS_GROUPS.CHINCHOUEVO,
  "Pichu": EVOLUTIONS_GROUPS.PICHUEVO,
  "Cleffa": EVOLUTIONS_GROUPS.CLEFFAEVO,
  "Igglybuff": EVOLUTIONS_GROUPS.IGGLYBUFFEVO,
  "Togepi": EVOLUTIONS_GROUPS.TOGEPIEVO,
  "Togetic": EVOLUTIONS_GROUPS.TOGEPIEVO,
  "Natu": EVOLUTIONS_GROUPS.NATUEVO,
  "Xatu": EVOLUTIONS_GROUPS.NATUEVO,
  "Mareep": EVOLUTIONS_GROUPS.MAREEPEVO,
  "Flaaffy": EVOLUTIONS_GROUPS.MAREEPEVO,
  "Ampharos": EVOLUTIONS_GROUPS.MAREEPEVO,
  "Bellossom": EVOLUTIONS_GROUPS.BELLOSSOM,
  "Marill": EVOLUTIONS_GROUPS.AZURILLEVO,
  "Azumarill": EVOLUTIONS_GROUPS.AZURILLEVO,
  "Sudowoodo": EVOLUTIONS_GROUPS.BONSLYEVO,
  "Politoed": EVOLUTIONS_GROUPS.POLITOED,
  "Hoppip": EVOLUTIONS_GROUPS.HOPPIPEVO,
  "Skiploom": EVOLUTIONS_GROUPS.HOPPIPEVO,
  "Jumpluff": EVOLUTIONS_GROUPS.HOPPIPEVO,
  "Aipom": EVOLUTIONS_GROUPS.AIPOMEVO,
  "Sunkern": EVOLUTIONS_GROUPS.SUNKERNEVO,
  "Sunflora": EVOLUTIONS_GROUPS.SUNKERNEVO,
  "Yanma": EVOLUTIONS_GROUPS.YANMAEVO,
  "Wooper": EVOLUTIONS_GROUPS.WOOPEREVO,
  "Quagsire": EVOLUTIONS_GROUPS.WOOPEREVO,
  "Espeon": EVOLUTIONS_GROUPS.ESPEON,
  "Umbreon": EVOLUTIONS_GROUPS.UMBREON,
  "Murkrow": EVOLUTIONS_GROUPS.MURKROWEVO,
  "Slowking": EVOLUTIONS_GROUPS.SLOWKING,
  "Misdreavus": EVOLUTIONS_GROUPS.MISDREAVUS,
  "Unown": EVOLUTIONS_GROUPS.UNOWN,
  "Wobbuffet": EVOLUTIONS_GROUPS.WYNAUTEVO,
  "Girafarig": EVOLUTIONS_GROUPS.GIRAFARIG,
  "Pineco": EVOLUTIONS_GROUPS.PINECOEVO,
  "Forretress": EVOLUTIONS_GROUPS.PINECOEVO,
  "Dunsparce": EVOLUTIONS_GROUPS.DUNSPARCE,
  "Gligar": EVOLUTIONS_GROUPS.GLIGAREVO,
  "Steelix": EVOLUTIONS_GROUPS.ONIXEVO,
  "Snubbull": EVOLUTIONS_GROUPS.SNUBBULLEVO,
  "Granbull": EVOLUTIONS_GROUPS.SNUBBULLEVO,
  "Qwilfish": EVOLUTIONS_GROUPS.QWILFISH,
  "Scizor": EVOLUTIONS_GROUPS.SCYTHEREVO,
  "Shuckle": EVOLUTIONS_GROUPS.SHUCKLE,
  "Heracross": EVOLUTIONS_GROUPS.HERACROSS,
  "Sneasel": EVOLUTIONS_GROUPS.SNEASELEVO,
  "Teddiursa": EVOLUTIONS_GROUPS.TEDDIURSAEVO,
  "Ursaring": EVOLUTIONS_GROUPS.TEDDIURSAEVO,
  "Slugma": EVOLUTIONS_GROUPS.SLUGMAEVO,
  "Magcargo": EVOLUTIONS_GROUPS.SLUGMAEVO,
  "Swinub": EVOLUTIONS_GROUPS.SWINUBEVO,
  "Piloswine": EVOLUTIONS_GROUPS.SWINUBEVO,
  "Corsola": EVOLUTIONS_GROUPS.CORSOLA,
  "Remoraid": EVOLUTIONS_GROUPS.REMORAIDEVO,
  "Octillery": EVOLUTIONS_GROUPS.REMORAIDEVO,
  "Delibird": EVOLUTIONS_GROUPS.DELIBIRD,
  "Mantine": EVOLUTIONS_GROUPS.MANTYKEEVO,
  "Skarmory": EVOLUTIONS_GROUPS.SKARMORY,
  "Houndour": EVOLUTIONS_GROUPS.HOUNDOUREVO,
  "Houndoom": EVOLUTIONS_GROUPS.HOUNDOUREVO,
  "Kingdra": EVOLUTIONS_GROUPS.HORSEAEVO,
  "Phanpy": EVOLUTIONS_GROUPS.PHANPYEVO,
  "Donphan": EVOLUTIONS_GROUPS.PHANPYEVO,
  "Porygon2": EVOLUTIONS_GROUPS.PORYGONEVO,
  "Stantler": EVOLUTIONS_GROUPS.STANTLER,
  "Smeargle": EVOLUTIONS_GROUPS.SMEARGLE,
  "Tyrogue": EVOLUTIONS_GROUPS.TYROGUE,
  "Hitmontop": EVOLUTIONS_GROUPS.HITMONTOP,
  "Smoochum": EVOLUTIONS_GROUPS.SMOOCHUMEVO,
  "Elekid": EVOLUTIONS_GROUPS.ELEKIDEVO,
  "Magby": EVOLUTIONS_GROUPS.MAGBYEVO,
  "Miltank": EVOLUTIONS_GROUPS.MILTANK,
  "Blissey": EVOLUTIONS_GROUPS.HAPPINYEVO,
  "Raikou": EVOLUTIONS_GROUPS.RAIKOU,
  "Entei": EVOLUTIONS_GROUPS.ENTEI,
  "Suicune": EVOLUTIONS_GROUPS.SUICUNE,
  "Larvitar": EVOLUTIONS_GROUPS.LARVITAREVO,
  "Pupitar": EVOLUTIONS_GROUPS.LARVITAREVO,
  "Tyranitar": EVOLUTIONS_GROUPS.LARVITAREVO,
  "Lugia": EVOLUTIONS_GROUPS.LUGIA,
  "Ho-oh": EVOLUTIONS_GROUPS.HOOH,
  "Celebi": EVOLUTIONS_GROUPS.CELEBI,
  "Treecko": EVOLUTIONS_GROUPS.TREECKOEVO,
  "Grovyle": EVOLUTIONS_GROUPS.TREECKOEVO,
  "Sceptile": EVOLUTIONS_GROUPS.TREECKOEVO,
  "Torchic": EVOLUTIONS_GROUPS.TORCHICEVO,
  "Combusken": EVOLUTIONS_GROUPS.TORCHICEVO,
  "Blaziken": EVOLUTIONS_GROUPS.TORCHICEVO,
  "Mudkip": EVOLUTIONS_GROUPS.MUDKIPEVO,
  "Marshtomp": EVOLUTIONS_GROUPS.MUDKIPEVO,
  "Swampert": EVOLUTIONS_GROUPS.MUDKIPEVO,
  "Poochyena": EVOLUTIONS_GROUPS.POOCHYENAEVO,
  "Mightyena": EVOLUTIONS_GROUPS.POOCHYENAEVO,
  "Zigzagoon": EVOLUTIONS_GROUPS.ZIGZAGOONEVO,
  "Linoone": EVOLUTIONS_GROUPS.ZIGZAGOONEVO,
  "Wurmple": EVOLUTIONS_GROUPS.WURMPLE,
  "Silcoon": EVOLUTIONS_GROUPS.SILCOONEVO,
  "Beautifly": EVOLUTIONS_GROUPS.SILCOONEVO,
  "Cascoon": EVOLUTIONS_GROUPS.CASCOONEVO,
  "Dustox": EVOLUTIONS_GROUPS.CASCOONEVO,
  "Lotad": EVOLUTIONS_GROUPS.LOTADEVO,
  "Lombre": EVOLUTIONS_GROUPS.LOTADEVO,
  "Ludicolo": EVOLUTIONS_GROUPS.LOTADEVO,
  "Seedot": EVOLUTIONS_GROUPS.SEEDOTEVO,
  "Nuzleaf": EVOLUTIONS_GROUPS.SEEDOTEVO,
  "Shiftry": EVOLUTIONS_GROUPS.SEEDOTEVO,
  "Taillow": EVOLUTIONS_GROUPS.TAILLOWEVO,
  "Swellow": EVOLUTIONS_GROUPS.TAILLOWEVO,
  "Wingull": EVOLUTIONS_GROUPS.WINGULLEVO,
  "Pelipper": EVOLUTIONS_GROUPS.WINGULLEVO,
  "Ralts": EVOLUTIONS_GROUPS.RALTSEVO,
  "Kirlia": EVOLUTIONS_GROUPS.RALTSEVO,
  "Gardevoir": EVOLUTIONS_GROUPS.GARDEVOIR,
  "Surskit": EVOLUTIONS_GROUPS.SURSKITEVO,
  "Masquerain": EVOLUTIONS_GROUPS.SURSKITEVO,
  "Shroomish": EVOLUTIONS_GROUPS.SHROOMISHEVO,
  "Breloom": EVOLUTIONS_GROUPS.SHROOMISHEVO,
  "Slakoth": EVOLUTIONS_GROUPS.SLAKOTHEVO,
  "Vigoroth": EVOLUTIONS_GROUPS.SLAKOTHEVO,
  "Slaking": EVOLUTIONS_GROUPS.SLAKOTHEVO,
  "Nincada": EVOLUTIONS_GROUPS.NINCADAEVO,
  "Ninjask": EVOLUTIONS_GROUPS.NINCADAEVO,
  "Shedinja": EVOLUTIONS_GROUPS.SHEDINJA,
  "Whismur": EVOLUTIONS_GROUPS.WHISMUREVO,
  "Loudred": EVOLUTIONS_GROUPS.WHISMUREVO,
  "Exploud": EVOLUTIONS_GROUPS.WHISMUREVO,
  "Makuhita": EVOLUTIONS_GROUPS.MAKUHITAEVO,
  "Hariyama": EVOLUTIONS_GROUPS.MAKUHITAEVO,
  "Azurill": EVOLUTIONS_GROUPS.AZURILLEVO,
  "Nosepass": EVOLUTIONS_GROUPS.NOSEPASSEVO,
  "Skitty": EVOLUTIONS_GROUPS.SKITTYEVO,
  "Delcatty": EVOLUTIONS_GROUPS.SKITTYEVO,
  "Sableye": EVOLUTIONS_GROUPS.SABLEYE,
  "Mawile": EVOLUTIONS_GROUPS.MAWILE,
  "Aron": EVOLUTIONS_GROUPS.ARONEVO,
  "Lairon": EVOLUTIONS_GROUPS.ARONEVO,
  "Aggron": EVOLUTIONS_GROUPS.ARONEVO,
  "Meditite": EVOLUTIONS_GROUPS.MEDITITEEVO,
  "Medicham": EVOLUTIONS_GROUPS.MEDITITEEVO,
  "Electrike": EVOLUTIONS_GROUPS.ELECTRIKEEVO,
  "Manectric": EVOLUTIONS_GROUPS.ELECTRIKEEVO,
  "Plusle": EVOLUTIONS_GROUPS.PLUSLE,
  "Minun": EVOLUTIONS_GROUPS.MINUN,
  "Volbeat": EVOLUTIONS_GROUPS.VOLBEAT,
  "Illumise": EVOLUTIONS_GROUPS.ILLUMISE,
  "Roselia": EVOLUTIONS_GROUPS.BUDEWEVO,
  "Gulpin": EVOLUTIONS_GROUPS.GULPINEVO,
  "Swalot": EVOLUTIONS_GROUPS.GULPINEVO,
  "Carvanha": EVOLUTIONS_GROUPS.CARVANHAEVO,
  "Sharpedo": EVOLUTIONS_GROUPS.CARVANHAEVO,
  "Wailmer": EVOLUTIONS_GROUPS.WAILMEREVO,
  "Wailord": EVOLUTIONS_GROUPS.WAILMEREVO,
  "Numel": EVOLUTIONS_GROUPS.NUMELEVO,
  "Camerupt": EVOLUTIONS_GROUPS.NUMELEVO,
  "Torkoal": EVOLUTIONS_GROUPS.TORKOAL,
  "Spoink": EVOLUTIONS_GROUPS.SPOINKEVO,
  "Grumpig": EVOLUTIONS_GROUPS.SPOINKEVO,
  "Spinda": EVOLUTIONS_GROUPS.SPINDA,
  "Trapinch": EVOLUTIONS_GROUPS.TRAPINCHEVO,
  "Vibrava": EVOLUTIONS_GROUPS.TRAPINCHEVO,
  "Flygon": EVOLUTIONS_GROUPS.TRAPINCHEVO,
  "Cacnea": EVOLUTIONS_GROUPS.CACNEAEVO,
  "Cacturne": EVOLUTIONS_GROUPS.CACNEAEVO,
  "Swablu": EVOLUTIONS_GROUPS.SWABLUEVO,
  "Altaria": EVOLUTIONS_GROUPS.SWABLUEVO,
  "Zangoose": EVOLUTIONS_GROUPS.ZANGOOSE,
  "Seviper": EVOLUTIONS_GROUPS.SEVIPER,
  "Lunatone": EVOLUTIONS_GROUPS.LUNATONE,
  "Solrock": EVOLUTIONS_GROUPS.SOLROCK,
  "Barboach": EVOLUTIONS_GROUPS.BARBOACHEVO,
  "Whiscash": EVOLUTIONS_GROUPS.BARBOACHEVO,
  "Corphish": EVOLUTIONS_GROUPS.CORPISHEVO,
  "Crawdaunt": EVOLUTIONS_GROUPS.CORPISHEVO,
  "Baltoy": EVOLUTIONS_GROUPS.BALTOYEVO,
  "Claydol": EVOLUTIONS_GROUPS.BALTOYEVO,
  "Lileep": EVOLUTIONS_GROUPS.LILEEPEVO,
  "Cradily": EVOLUTIONS_GROUPS.LILEEPEVO,
  "Anorith": EVOLUTIONS_GROUPS.ANORITHEVO,
  "Armaldo": EVOLUTIONS_GROUPS.ANORITHEVO,
  "Feebas": EVOLUTIONS_GROUPS.FEEBAS,
  "Milotic": EVOLUTIONS_GROUPS.FEEBAS,
  "Castform": EVOLUTIONS_GROUPS.CASTFORM,
  "Kecleon": EVOLUTIONS_GROUPS.KECKLEON,
  "Shuppet": EVOLUTIONS_GROUPS.SHUPPETEVO,
  "Banette": EVOLUTIONS_GROUPS.SHUPPETEVO,
  "Duskull": EVOLUTIONS_GROUPS.DUSKULLEVO,
  "Dusclops": EVOLUTIONS_GROUPS.DUSKULLEVO,
  "Tropius": EVOLUTIONS_GROUPS.TROPIUS,
  "Chimecho": EVOLUTIONS_GROUPS.CHINGLINGEVO,
  "Absol": EVOLUTIONS_GROUPS.ABSOL,
  "Wynaut": EVOLUTIONS_GROUPS.WYNAUTEVO,
  "Snorunt": EVOLUTIONS_GROUPS.SNORUNT,
  "Glalie": EVOLUTIONS_GROUPS.GLALIE,
  "Spheal": EVOLUTIONS_GROUPS.SPHEALEVO,
  "Sealeo": EVOLUTIONS_GROUPS.SPHEALEVO,
  "Walrein": EVOLUTIONS_GROUPS.SPHEALEVO,
  "Clamperl": EVOLUTIONS_GROUPS.CLAMPERL,
  "Huntail": EVOLUTIONS_GROUPS.HUNTAIL,
  "Gorebyss": EVOLUTIONS_GROUPS.GOREBYSS,
  "Relicanth": EVOLUTIONS_GROUPS.RELICANTH,
  "Luvdisc": EVOLUTIONS_GROUPS.LUVDISC,
  "Bagon": EVOLUTIONS_GROUPS.BAGONEVO,
  "Shelgon": EVOLUTIONS_GROUPS.BAGONEVO,
  "Salamence": EVOLUTIONS_GROUPS.BAGONEVO,
  "Beldum": EVOLUTIONS_GROUPS.BELDUMEVO,
  "Metang": EVOLUTIONS_GROUPS.BELDUMEVO,
  "Metagross": EVOLUTIONS_GROUPS.BELDUMEVO,
  "Regirock": EVOLUTIONS_GROUPS.REGIROCK,
  "Regice": EVOLUTIONS_GROUPS.REGICE,
  "Registeel": EVOLUTIONS_GROUPS.REGISTEEL,
  "Latias": EVOLUTIONS_GROUPS.LATIAS,
  "Latios": EVOLUTIONS_GROUPS.LATIOS,
  "Kyogre": EVOLUTIONS_GROUPS.KYOGRE,
  "Groudon": EVOLUTIONS_GROUPS.GROUDON,
  "Rayquaza": EVOLUTIONS_GROUPS.RAYQUAZA,
  "Jirachi": EVOLUTIONS_GROUPS.JIRACHI,
  "Deoxys": EVOLUTIONS_GROUPS.DEOXYS,
  "Deoxys-attack": EVOLUTIONS_GROUPS.DEOXYSATTACK,
  "Deoxys-defense": EVOLUTIONS_GROUPS.DEOXISDEFENSE,
  "Deoxys-speed": EVOLUTIONS_GROUPS.DEOXYSSPEED,
  "Turtwig": EVOLUTIONS_GROUPS.TURTWIGEVO,
  "Grotle": EVOLUTIONS_GROUPS.TURTWIGEVO,
  "Torterra": EVOLUTIONS_GROUPS.TURTWIGEVO,
  "Chimchar": EVOLUTIONS_GROUPS.CHIMCHAREVO,
  "Monferno": EVOLUTIONS_GROUPS.CHIMCHAREVO,
  "Infernape": EVOLUTIONS_GROUPS.CHIMCHAREVO,
  "Piplup": EVOLUTIONS_GROUPS.PIPLUPEVO,
  "Prinplup": EVOLUTIONS_GROUPS.PIPLUPEVO,
  "Empoleon": EVOLUTIONS_GROUPS.PIPLUPEVO,
  "Starly": EVOLUTIONS_GROUPS.STARLYEVO,
  "Staravia": EVOLUTIONS_GROUPS.STARLYEVO,
  "Staraptor": EVOLUTIONS_GROUPS.STARLYEVO,
  "Bidoof": EVOLUTIONS_GROUPS.BIDOOFEVO,
  "Bibarel": EVOLUTIONS_GROUPS.BIDOOFEVO,
  "Kricketot": EVOLUTIONS_GROUPS.KRICKETOTEVO,
  "Kricketune": EVOLUTIONS_GROUPS.KRICKETOTEVO,
  "Shinx": EVOLUTIONS_GROUPS.SHINXEVO,
  "Luxio": EVOLUTIONS_GROUPS.SHINXEVO,
  "Luxray": EVOLUTIONS_GROUPS.SHINXEVO,
  "Budew": EVOLUTIONS_GROUPS.BUDEWEVO,
  "Roserade": EVOLUTIONS_GROUPS.BUDEWEVO,
  "Cranidos": EVOLUTIONS_GROUPS.CRANIDOSEVO,
  "Rampardos": EVOLUTIONS_GROUPS.CRANIDOSEVO,
  "Shieldon": EVOLUTIONS_GROUPS.SHIELDONEVO,
  "Bastiodon": EVOLUTIONS_GROUPS.SHIELDONEVO,
  "Burmy": EVOLUTIONS_GROUPS.BURMY,
  "Wormadam-plant": EVOLUTIONS_GROUPS.WORMADAMPLANT,
  "Wormadam-sandy": EVOLUTIONS_GROUPS.WORMADAMSANDY,
  "Wormadam-trash": EVOLUTIONS_GROUPS.WORMADAMTRASH,
  "Mothim": EVOLUTIONS_GROUPS.MOTHIM,
  "Combee": EVOLUTIONS_GROUPS.COMBEEEVO,
  "Vespiquen": EVOLUTIONS_GROUPS.COMBEEEVO,
  "Pachirisu": EVOLUTIONS_GROUPS.PACHIRISU,
  "Buizel": EVOLUTIONS_GROUPS.BUIZELEVO,
  "Floatzel": EVOLUTIONS_GROUPS.BUIZELEVO,
  "Cherubi": EVOLUTIONS_GROUPS.CHERUBIEVO,
  "Cherrim": EVOLUTIONS_GROUPS.CHERUBIEVO,
  "Shellos": EVOLUTIONS_GROUPS.SHELLOSEVO,
  "Gastrodon": EVOLUTIONS_GROUPS.SHELLOSEVO,
  "Ambipom": EVOLUTIONS_GROUPS.AIPOMEVO,
  "Drifloon": EVOLUTIONS_GROUPS.DRIFLOONEVO,
  "Drifblim": EVOLUTIONS_GROUPS.DRIFLOONEVO,
  "Buneary": EVOLUTIONS_GROUPS.BUNEARYEVO,
  "Lopunny": EVOLUTIONS_GROUPS.BUNEARYEVO,
  "Mismagius": EVOLUTIONS_GROUPS.MISDREAVUS,
  "Honchkrow": EVOLUTIONS_GROUPS.MURKROWEVO,
  "Glameow": EVOLUTIONS_GROUPS.GLAMEOWEVO,
  "Purugly": EVOLUTIONS_GROUPS.GLAMEOWEVO,
  "Chingling": EVOLUTIONS_GROUPS.CHINGLINGEVO,
  "Stunky": EVOLUTIONS_GROUPS.STUNKYEVO,
  "Skuntank": EVOLUTIONS_GROUPS.STUNKYEVO,
  "Bronzor": EVOLUTIONS_GROUPS.BRONZOREVO,
  "Bronzong": EVOLUTIONS_GROUPS.BRONZOREVO,
  "Bonsly": EVOLUTIONS_GROUPS.BONSLYEVO,
  "Mime-jr": EVOLUTIONS_GROUPS.MIMEJREVO,
  "Happiny": EVOLUTIONS_GROUPS.HAPPINYEVO,
  "Chatot": EVOLUTIONS_GROUPS.CHATOT,
  "Spiritomb": EVOLUTIONS_GROUPS.SPIRITOMB,
  "Gible": EVOLUTIONS_GROUPS.GIBLEEVO,
  "Gabite": EVOLUTIONS_GROUPS.GIBLEEVO,
  "Garchomp": EVOLUTIONS_GROUPS.GIBLEEVO,
  "Munchlax": EVOLUTIONS_GROUPS.MUNCHLAXEVO,
  "Riolu": EVOLUTIONS_GROUPS.RIOLUEVO,
  "Lucario": EVOLUTIONS_GROUPS.RIOLUEVO,
  "Hippopotas": EVOLUTIONS_GROUPS.HIPPOPOTASEVO,
  "Hippowdon": EVOLUTIONS_GROUPS.HIPPOPOTASEVO,
  "Skorupi": EVOLUTIONS_GROUPS.SKORUPIEVO,
  "Drapion": EVOLUTIONS_GROUPS.SKORUPIEVO,
  "Croagunk": EVOLUTIONS_GROUPS.CROAGUNKEVO,
  "Toxicroak": EVOLUTIONS_GROUPS.CROAGUNKEVO,
  "Carnivine": EVOLUTIONS_GROUPS.CARNIVINE,
  "Finneon": EVOLUTIONS_GROUPS.FINNEONEVO,
  "Lumineon": EVOLUTIONS_GROUPS.FINNEONEVO,
  "Mantyke": EVOLUTIONS_GROUPS.MANTYKEEVO,
  "Snover": EVOLUTIONS_GROUPS.SNOVEREVO,
  "Abomasnow": EVOLUTIONS_GROUPS.SNOVEREVO,
  "Weavile": EVOLUTIONS_GROUPS.SNEASELEVO,
  "Magnezone": EVOLUTIONS_GROUPS.MAGNEMITEEVO,
  "Lickilicky": EVOLUTIONS_GROUPS.LICKYTUNGEVO,
  "Rhyperior": EVOLUTIONS_GROUPS.RHYHORNEVO,
  "Tangrowth": EVOLUTIONS_GROUPS.TANGELAEVO,
  "Electivire": EVOLUTIONS_GROUPS.ELEKIDEVO,
  "Magmortar": EVOLUTIONS_GROUPS.MAGBYEVO,
  "Togekiss": EVOLUTIONS_GROUPS.TOGEPIEVO,
  "Yanmega": EVOLUTIONS_GROUPS.YANMAEVO,
  "Leafeon": EVOLUTIONS_GROUPS.LEAFEON,
  "Glaceon": EVOLUTIONS_GROUPS.GLACEON,
  "Gliscor": EVOLUTIONS_GROUPS.GLIGAREVO,
  "Mamoswine": EVOLUTIONS_GROUPS.SWINUBEVO,
  "Porygon-Z": EVOLUTIONS_GROUPS.PORYGONEVO,
  "Gallade": EVOLUTIONS_GROUPS.GALLADE,
  "Probopass": EVOLUTIONS_GROUPS.NOSEPASSEVO,
  "Dusknoir": EVOLUTIONS_GROUPS.DUSKULLEVO,
  "Froslass": EVOLUTIONS_GROUPS.FROSLASS,
  "Rotom": EVOLUTIONS_GROUPS.ROTOM,
  "Rotom-heat": EVOLUTIONS_GROUPS.ROTOMHEAT,
  "Rotom-wash": EVOLUTIONS_GROUPS.ROTOMWASH,
  "Rotom-frost": EVOLUTIONS_GROUPS.ROTOMFROST,
  "Rotom-fan": EVOLUTIONS_GROUPS.ROTOMFAN,
  "Rotom-mow": EVOLUTIONS_GROUPS.ROTOMMOW,
  "Uxie": EVOLUTIONS_GROUPS.UXIE,
  "Mesprit": EVOLUTIONS_GROUPS.MESPRIT,
  "Azelf": EVOLUTIONS_GROUPS.AZELF,
  "Dialga": EVOLUTIONS_GROUPS.DIALGA,
  "Palkia": EVOLUTIONS_GROUPS.PALKIA,
  "Heatran": EVOLUTIONS_GROUPS.HEATRAN,
  "Regigigas": EVOLUTIONS_GROUPS.REGIGIGAS,
  "Giratina-altered": EVOLUTIONS_GROUPS.GIRATINAALTERED,
  "Giratina-origin": EVOLUTIONS_GROUPS.GIRATINAORIGIN,
  "Cresselia": EVOLUTIONS_GROUPS.CRESSELIA,
  "Phione": EVOLUTIONS_GROUPS.PHIONE,
  "Manaphy": EVOLUTIONS_GROUPS.MANAPHY,
  "Darkrai": EVOLUTIONS_GROUPS.DARKRAI,
  "Shaymin-land": EVOLUTIONS_GROUPS.SHAYMINLAND,
  "Shaymin-sky": EVOLUTIONS_GROUPS.SHAYMINSKY,
  "Arceus": EVOLUTIONS_GROUPS.ARCEUS,
}

export const POKEMON_IMAGES_LIST = [
  "Bulbasaur",
  "Ivysaur",
  "Venusaur",
  "Charmander",
  "Charmeleon",
  "Charizard",
  "Squirtle",
  "Wartortle",
  "Blastoise",
  "Caterpie",
  "Metapod",
  "Butterfree",
  "Weedle",
  "Kakuna",
  "Beedrill",
  "Pidgey",
  "Pidgeotto",
  "Pidgeot",
  "Rattata",
  "Raticate",
  "Spearow",
  "Fearow",
  "Ekans",
  "Arbok",
  "Pikachu",
  "Raichu",
  "Sandshrew",
  "Sandslash",
  "NidoranF",
  "Nidorina",
  "Nidoqueen",
  "NidoranM",
  "Nidorino",
  "Nidoking",
  "Clefairy",
  "Clefable",
  "Vulpix",
  "Ninetales",
  "Jigglypuff",
  "Wigglytuff",
  "Zubat",
  "Golbat",
  "Oddish",
  "Gloom",
  "Vileplume",
  "Paras",
  "Parasect",
  "Venonat",
  "Venomoth",
  "Diglett",
  "Dugtrio",
  "Meowth",
  "Persian",
  "Psyduck",
  "Golduck",
  "Mankey",
  "Primeape",
  "Growlithe",
  "Arcanine",
  "Poliwag",
  "Poliwhirl",
  "Poliwrath",
  "Abra",
  "Kadabra",
  "Alakazam",
  "Machop",
  "Machoke",
  "Machamp",
  "Bellsprout",
  "Weepinbell",
  "Victreebel",
  "Tentacool",
  "Tentacruel",
  "Geodude",
  "Graveler",
  "Golem",
  "Ponyta",
  "Rapidash",
  "Slowpoke",
  "Slowbro",
  "Magnemite",
  "Magneton",
  "Farfetch'd",
  "Doduo",
  "Dodrio",
  "Seel",
  "Dewgong",
  "Grimer",
  "Muk",
  "Shellder",
  "Cloyster",
  "Gastly",
  "Haunter",
  "Gengar",
  "Onix",
  "Drowzee",
  "Hypno",
  "Krabby",
  "Kingler",
  "Voltorb",
  "Electrode",
  "Exeggcute",
  "Exeggutor",
  "Cubone",
  "Marowak",
  "Hitmonlee",
  "Hitmonchan",
  "Lickitung",
  "Koffing",
  "Weezing",
  "Rhyhorn",
  "Rhydon",
  "Chansey",
  "Tangela",
  "Kangaskhan",
  "Horsea",
  "Seadra",
  "Goldeen",
  "Seaking",
  "Staryu",
  "Starmie",
  "Mr.Mime",
  "Scyther",
  "Jynx",
  "Electabuzz",
  "Magmar",
  "Pinsir",
  "Tauros",
  "Magikarp",
  "Gyarados",
  "Lapras",
  "Ditto",
  "Eevee",
  "Vaporeon",
  "Jolteon",
  "Flareon",
  "Porygon",
  "Omanyte",
  "Omastar",
  "Kabuto",
  "Kabutops",
  "Aerodactyl",
  "Snorlax",
  "Articuno",
  "Zapdos",
  "Moltres",
  "Dratini",
  "Dragonair",
  "Dragonite",
  "Mewtwo",
  "Mew",
  "Chikorita",
  "Bayleef",
  "Meganium",
  "Cyndaquil",
  "Quilava",
  "Typhlosion",
  "Totodile",
  "Croconaw",
  "Feraligatr",
  "Sentret",
  "Furret",
  "Hoothoot",
  "Noctowl",
  "Ledyba",
  "Ledian",
  "Spinarak",
  "Ariados",
  "Crobat",
  "Chinchou",
  "Lanturn",
  "Pichu",
  "Cleffa",
  "Igglybuff",
  "Togepi",
  "Togetic",
  "Natu",
  "Xatu",
  "Mareep",
  "Flaaffy",
  "Ampharos",
  "Bellossom",
  "Marill",
  "Azumarill",
  "Sudowoodo",
  "Politoed",
  "Hoppip",
  "Skiploom",
  "Jumpluff",
  "Aipom",
  "Sunkern",
  "Sunflora",
  "Yanma",
  "Wooper",
  "Quagsire",
  "Espeon",
  "Umbreon",
  "Murkrow",
  "Slowking",
  "Misdreavus",
  "Unown",
  "Wobbuffet",
  "Girafarig",
  "Pineco",
  "Forretress",
  "Dunsparce",
  "Gligar",
  "Steelix",
  "Snubbull",
  "Granbull",
  "Qwilfish",
  "Scizor",
  "Shuckle",
  "Heracross",
  "Sneasel",
  "Teddiursa",
  "Ursaring",
  "Slugma",
  "Magcargo",
  "Swinub",
  "Piloswine",
  "Corsola",
  "Remoraid",
  "Octillery",
  "Delibird",
  "Mantine",
  "Skarmory",
  "Houndour",
  "Houndoom",
  "Kingdra",
  "Phanpy",
  "Donphan",
  "Porygon2",
  "Stantler",
  "Smeargle",
  "Tyrogue",
  "Hitmontop",
  "Smoochum",
  "Elekid",
  "Magby",
  "Miltank",
  "Blissey",
  "Raikou",
  "Entei",
  "Suicune",
  "Larvitar",
  "Pupitar",
  "Tyranitar",
  "Lugia",
  "Ho-oh",
  "Celebi",
  "Treecko",
  "Grovyle",
  "Sceptile",
  "Torchic",
  "Combusken",
  "Blaziken",
  "Mudkip",
  "Marshtomp",
  "Swampert",
  "Poochyena",
  "Mightyena",
  "Zigzagoon",
  "Linoone",
  "Wurmple",
  "Silcoon",
  "Beautifly",
  "Cascoon",
  "Dustox",
  "Lotad",
  "Lombre",
  "Ludicolo",
  "Seedot",
  "Nuzleaf",
  "Shiftry",
  "Taillow",
  "Swellow",
  "Wingull",
  "Pelipper",
  "Ralts",
  "Kirlia",
  "Gardevoir",
  "Surskit",
  "Masquerain",
  "Shroomish",
  "Breloom",
  "Slakoth",
  "Vigoroth",
  "Slaking",
  "Nincada",
  "Ninjask",
  "Shedinja",
  "Whismur",
  "Loudred",
  "Exploud",
  "Makuhita",
  "Hariyama",
  "Azurill",
  "Nosepass",
  "Skitty",
  "Delcatty",
  "Sableye",
  "Mawile",
  "Aron",
  "Lairon",
  "Aggron",
  "Meditite",
  "Medicham",
  "Electrike",
  "Manectric",
  "Plusle",
  "Minun",
  "Volbeat",
  "Illumise",
  "Roselia",
  "Gulpin",
  "Swalot",
  "Carvanha",
  "Sharpedo",
  "Wailmer",
  "Wailord",
  "Numel",
  "Camerupt",
  "Torkoal",
  "Spoink",
  "Grumpig",
  "Spinda",
  "Trapinch",
  "Vibrava",
  "Flygon",
  "Cacnea",
  "Cacturne",
  "Swablu",
  "Altaria",
  "Zangoose",
  "Seviper",
  "Lunatone",
  "Solrock",
  "Barboach",
  "Whiscash",
  "Corphish",
  "Crawdaunt",
  "Baltoy",
  "Claydol",
  "Lileep",
  "Cradily",
  "Anorith",
  "Armaldo",
  "Feebas",
  "Milotic",
  "Castform",
  "Kecleon",
  "Shuppet",
  "Banette",
  "Duskull",
  "Dusclops",
  "Tropius",
  "Chimecho",
  "Absol",
  "Wynaut",
  "Snorunt",
  "Glalie",
  "Spheal",
  "Sealeo",
  "Walrein",
  "Clamperl",
  "Huntail",
  "Gorebyss",
  "Relicanth",
  "Luvdisc",
  "Bagon",
  "Shelgon",
  "Salamence",
  "Beldum",
  "Metang",
  "Metagross",
  "Regirock",
  "Regice",
  "Registeel",
  "Latias",
  "Latios",
  "Kyogre",
  "Groudon",
  "Rayquaza",
  "Jirachi",
  "Deoxys",
  "Turtwig",
  "Grotle",
  "Torterra",
  "Chimchar",
  "Monferno",
  "Infernape",
  "Piplup",
  "Prinplup",
  "Empoleon",
  "Starly",
  "Staravia",
  "Staraptor",
  "Bidoof",
  "Bibarel",
  "Kricketot",
  "Kricketune",
  "Shinx",
  "Luxio",
  "Luxray",
  "Budew",
  "Roserade",
  "Cranidos",
  "Rampardos",
  "Shieldon",
  "Bastiodon",
  "Burmy",
  "Wormadam-plant",
  "Wormadam-sandy",
  "Wormadam-trash",
  "Mothim",
  "Combee",
  "Vespiquen",
  "Pachirisu",
  "Buizel",
  "Floatzel",
  "Cherubi",
  "Cherrim",
  "Shellos",
  "Gastrodon",
  "Ambipom",
  "Drifloon",
  "Drifblim",
  "Buneary",
  "Lopunny",
  "Mismagius",
  "Honchkrow",
  "Glameow",
  "Purugly",
  "Chingling",
  "Stunky",
  "Skuntank",
  "Bronzor",
  "Bronzong",
  "Bonsly",
  "Mime-jr",
  "Happiny",
  "Chatot",
  "Spiritomb",
  "Gible",
  "Gabite",
  "Garchomp",
  "Munchlax",
  "Riolu",
  "Lucario",
  "Hippopotas",
  "Hippowdon",
  "Skorupi",
  "Drapion",
  "Croagunk",
  "Toxicroak",
  "Carnivine",
  "Finneon",
  "Lumineon",
  "Mantyke",
  "Snover",
  "Abomasnow",
  "Weavile",
  "Magnezone",
  "Lickilicky",
  "Rhyperior",
  "Tangrowth",
  "Electivire",
  "Magmortar",
  "Togekiss",
  "Yanmega",
  "Leafeon",
  "Glaceon",
  "Gliscor",
  "Mamoswine",
  "Porygon-Z",
  "Gallade",
  "Probopass",
  "Dusknoir",
  "Froslass",
  "Rotom",
  "Rotom-heat",
  "Rotom-wash",
  "Rotom-frost",
  "Rotom-fan",
  "Rotom-mow",
  "Uxie",
  "Mesprit",
  "Azelf",
  "Dialga",
  "Palkia",
  "Heatran",
  "Regigigas",
  "Giratina-altered",
  "Giratina-origin",
  "Cresselia",
  "Phione",
  "Manaphy",
  "Darkrai",
  "Shaymin-land",
  "Shaymin-sky",
  "Arceus"
]
